
CREATE TABLE PLT_CUSTCO_STNG
(
	CUSTCO_ID             number(19,0)  NOT NULL ,
	ATTR_ID               number(19,0)  NOT NULL ,
	ATTR_VL               VARCHAR2(500)  NULL 
);



CREATE UNIQUE INDEX PLT_CUSTCO_STNG_PK ON PLT_CUSTCO_STNG
(CUSTCO_ID  ASC,ATTR_ID  ASC);



ALTER TABLE PLT_CUSTCO_STNG
	ADD PRIMARY KEY (CUSTCO_ID,ATTR_ID);



CREATE INDEX PLT_CUSTCO_STNG_F1 ON PLT_CUSTCO_STNG
(CUSTCO_ID  ASC);



CREATE INDEX PLT_CUSTCO_STNG_F2 ON PLT_CUSTCO_STNG
(ATTR_ID  ASC);



ALTER TABLE PLT_CUSTCO_STNG
	ADD CONSTRAINT  R_CUSTCO_STNG_2__CUSTCO_fd FOREIGN KEY (CUSTCO_ID) REFERENCES PLT_CUSTCO(CUSTCO_ID);



ALTER TABLE PLT_CUSTCO_STNG
	ADD CONSTRAINT  R_CUSTCO_STNG_2__EXPSN_ATTR_f1 FOREIGN KEY (ATTR_ID) REFERENCES PLT_EXPSN_ATTR(ATTR_ID);



COMMENT ON TABLE PLT_CUSTCO_STNG IS '고객사_설정';
COMMENT ON COLUMN PLT_CUSTCO_STNG.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CUSTCO_STNG.ATTR_ID IS '속성_ID';
COMMENT ON COLUMN PLT_CUSTCO_STNG.ATTR_VL IS '속성_값';
