ALTER TABLE PLT_KMS_CONTS ADD FILE_GROUP_KEY VARCHAR(90) NULL;
COMMENT ON COLUMN PLT_KMS_CONTS.FILE_GROUP_KEY IS '파일_그룹_키';
ALTER TABLE PLT_KMS_CONTS ADD SE_CD VARCHAR(60) NULL;
COMMENT ON COLUMN PLT_KMS_CONTS.SE_CD IS '구분_코드';
ALTER TABLE PLT_KMS_CONTS ADD ESNTL_YN CHAR(1) NULL;
COMMENT ON COLUMN PLT_KMS_CONTS.ESNTL_YN IS '필수_여부';



CREATE TABLE PLT_KMS_CONTS_CN
(
	KMS_CONTS_ID          number(19,0)  NOT NULL ,
	KMS_CONTS_CN          CLOB  NULL 
);



CREATE UNIQUE INDEX PLT_KMS_CONTS_CN_PK ON PLT_KMS_CONTS_CN
(KMS_CONTS_ID  ASC);



ALTER TABLE PLT_KMS_CONTS_CN
	ADD PRIMARY KEY (KMS_CONTS_ID);




CREATE TABLE PLT_KMS_CONTS_KEYWD
(
	KMS_KEYWD_ID          number(19,0)  NOT NULL ,
	KMS_CONTS_ID          number(19,0)  NULL ,
	KMS_KEYWD_NM          VARCHAR(100)  NULL 
);



CREATE UNIQUE INDEX PLT_KMS_CONTS_KEYWD_PK ON PLT_KMS_CONTS_KEYWD
(KMS_KEYWD_ID  ASC);



ALTER TABLE PLT_KMS_CONTS_KEYWD
	ADD PRIMARY KEY (KMS_KEYWD_ID);



CREATE INDEX PLT_KMS_CONTS_KEYWD_F1 ON PLT_KMS_CONTS_KEYWD
(KMS_CONTS_ID  ASC);



CREATE TABLE PLT_KMS_REL_CONTS
(
	KMS_REL_CONTS_ID      number(19,0)  NOT NULL ,
	KMS_CONTS_ID          number(19,0)  NOT NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               number(19,0)  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               number(19,0)  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_KMS_REL_CONTS_PK ON PLT_KMS_REL_CONTS
(KMS_REL_CONTS_ID  ASC,KMS_CONTS_ID  ASC);



ALTER TABLE PLT_KMS_REL_CONTS
	ADD PRIMARY KEY (KMS_REL_CONTS_ID,KMS_CONTS_ID);



CREATE INDEX PLT_KMS_REL_CONTS_F1 ON PLT_KMS_REL_CONTS
(KMS_CONTS_ID  ASC);



CREATE TABLE PLT_KMS_REL_LNK
(
	KMS_REL_LNK_ID        number(19,0)  NOT NULL ,
	KMS_CONTS_ID          number(19,0)  NULL ,
	REL_LNK_NM            VARCHAR(200)  NULL ,
	REL_LNK_URL           VARCHAR(600)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               number(19,0)  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               number(19,0)  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_KMS_REL_LNK_PK ON PLT_KMS_REL_LNK
(KMS_REL_LNK_ID  ASC);



ALTER TABLE PLT_KMS_REL_LNK
	ADD PRIMARY KEY (KMS_REL_LNK_ID);



CREATE INDEX PLT_KMS_REL_LNK_F1 ON PLT_KMS_REL_LNK
(KMS_CONTS_ID  ASC);



ALTER TABLE PLT_KMS_CONTS_CN
	ADD CONSTRAINT  R_KMS_CONTS_CN_2__KMS_CONTS_43 FOREIGN KEY (KMS_CONTS_ID) REFERENCES PLT_KMS_CONTS(KMS_CONTS_ID);



ALTER TABLE PLT_KMS_CONTS_KEYWD
	ADD CONSTRAINT  R_KMS_CONTS_KEYWD_2__KMS_CONTS FOREIGN KEY (KMS_CONTS_ID) REFERENCES PLT_KMS_CONTS(KMS_CONTS_ID);



ALTER TABLE PLT_KMS_REL_CONTS
	ADD CONSTRAINT  R_KMS_REL_CONTS_2__KMS_CONTS_7 FOREIGN KEY (KMS_CONTS_ID) REFERENCES PLT_KMS_CONTS(KMS_CONTS_ID);



ALTER TABLE PLT_KMS_REL_LNK
	ADD CONSTRAINT  R_KMS_REL_LNK_2__KMS_CONTS_c7 FOREIGN KEY (KMS_CONTS_ID) REFERENCES PLT_KMS_CONTS(KMS_CONTS_ID);



COMMENT ON TABLE PLT_KMS_CONTS_CN IS 'KMS_콘텐츠_내용';
COMMENT ON COLUMN PLT_KMS_CONTS_CN.KMS_CONTS_ID IS 'KMS_콘텐츠_ID';
COMMENT ON COLUMN PLT_KMS_CONTS_CN.KMS_CONTS_CN IS 'KMS_콘텐츠_내용';

COMMENT ON TABLE PLT_KMS_CONTS_KEYWD IS 'KMS_콘텐츠_키워드';
COMMENT ON COLUMN PLT_KMS_CONTS_KEYWD.KMS_KEYWD_ID IS 'KMS_키워드_ID';
COMMENT ON COLUMN PLT_KMS_CONTS_KEYWD.KMS_KEYWD_NM IS 'KMS_키워드_명';
COMMENT ON COLUMN PLT_KMS_CONTS_KEYWD.KMS_CONTS_ID IS 'KMS_콘텐츠_ID';

COMMENT ON TABLE PLT_KMS_REL_CONTS IS 'KMS_관계_콘텐츠';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.KMS_REL_CONTS_ID IS 'KMS_관계_콘텐츠_ID';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.KMS_CONTS_ID IS 'KMS_콘텐츠_ID';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_KMS_REL_CONTS.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_KMS_REL_LNK IS 'KMS_관계_링크';
COMMENT ON COLUMN PLT_KMS_REL_LNK.KMS_REL_LNK_ID IS 'KMS_관계_링크_ID';
COMMENT ON COLUMN PLT_KMS_REL_LNK.REL_LNK_NM IS '관계_링크_명';
COMMENT ON COLUMN PLT_KMS_REL_LNK.REL_LNK_URL IS '관계_링크_URL';
COMMENT ON COLUMN PLT_KMS_REL_LNK.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_KMS_REL_LNK.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_KMS_REL_LNK.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_KMS_REL_LNK.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_KMS_REL_LNK.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_KMS_REL_LNK.KMS_CONTS_ID IS 'KMS_콘텐츠_ID';


DROP TABLE PLT_KMS_CONTS_GUIDE_CN;
DROP TABLE PLT_KMS_CONTS_GUIDE_KEYWD;
DROP TABLE PLT_KMS_CONTS_REL_GUIDE;
DROP TABLE PLT_KMS_GUIDE_REL_LNK;
DROP TABLE PLT_KMS_CONTS_GUIDE_CUTT;
DROP TABLE PLT_KMS_CONTS_GUIDE;
