ALTER TABLE PLT_MENU ADD (MENU_NM_ENG VARCHAR2(300) NULL);

ALTER TABLE PLT_MENU ADD (MENU_EXPLN_ENG VARCHAR2(2000) NULL);


COMMENT ON COLUMN PLT_MENU.MENU_NM_ENG IS '메뉴_명_영문';
COMMENT ON COLUMN PLT_MENU.MENU_EXPLN_ENG IS '메뉴_설명_영문';

ALTER TABLE PLT_COMM_CD ADD (CD_NM_ENG VARCHAR2(300)  NULL);
COMMENT ON COLUMN PLT_COMM_CD.CD_NM_ENG IS '코드_명_영문';