ALTER TABLE PLT_CUTT_TYPE_STNG ADD STT_USE_YN            CHAR(1)  NULL;
ALTER TABLE PLT_CUTT_TYPE_STNG ADD TRANS_USE_YN          CHAR(1)  NULL;
COMMENT ON COLUMN PLT_CUTT_TYPE_STNG.STT_USE_YN IS 'STT_사용_여부';
COMMENT ON COLUMN PLT_CUTT_TYPE_STNG.TRANS_USE_YN IS '번역_사용_여부';