
CREATE TABLE PLT_USER_CUTT_TYPE_BMK
(
	USER_ID               BIGINT  NOT NULL ,
	CUTT_TYPE_ID          BIGINT  NOT NULL ,
	REG_SE_CD             VARCHAR(60)  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_USER_CUTT_TYPE_BMK_PK ON PLT_USER_CUTT_TYPE_BMK
(USER_ID  ASC,CUTT_TYPE_ID  ASC,REG_SE_CD  ASC);



ALTER TABLE PLT_USER_CUTT_TYPE_BMK
	ADD PRIMARY KEY (USER_ID,CUTT_TYPE_ID,REG_SE_CD);



CREATE INDEX PLT_USER_CUTT_TYPE_BMK_F1 ON PLT_USER_CUTT_TYPE_BMK
(USER_ID  ASC);



CREATE INDEX PLT_USER_CUTT_TYPE_BMK_F2 ON PLT_USER_CUTT_TYPE_BMK
(CUTT_TYPE_ID  ASC);



ALTER TABLE PLT_USER_CUTT_TYPE_BMK
	ADD CONSTRAINT  R_USER_CUTT_TYPE_BMK_2__USER_d FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_USER_CUTT_TYPE_BMK
	ADD CONSTRAINT  R_USER_CUTT_TYPE_BMK_2__CUTT_T FOREIGN KEY (CUTT_TYPE_ID) REFERENCES PLT_CUTT_TYPE(CUTT_TYPE_ID);



COMMENT ON TABLE PLT_USER_CUTT_TYPE_BMK IS '사용자_상담_유형_책갈피';
COMMENT ON COLUMN PLT_USER_CUTT_TYPE_BMK.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_CUTT_TYPE_BMK.CUTT_TYPE_ID IS '상담_유형_ID';
COMMENT ON COLUMN PLT_USER_CUTT_TYPE_BMK.REG_SE_CD IS '등록_구분_코드';
COMMENT ON COLUMN PLT_USER_CUTT_TYPE_BMK.REG_DT IS '등록_일시';


ALTER TABLE PLT_MTS_SNDNG_HSTRY ADD SRVY_TRGT_ID          BIGINT  NULL;
COMMENT ON COLUMN PLT_MTS_SNDNG_HSTRY.SRVY_TRGT_ID IS '설문_대상_ID';

CREATE INDEX PLT_MTS_SNDNG_HSTRY_F2 ON PLT_MTS_SNDNG_HSTRY
(SRVY_TRGT_ID  ASC);

ALTER TABLE PLT_MTS_SNDNG_HSTRY
	ADD CONSTRAINT  R_MTS_SNDNG_HSTRY_2__SRVY_TRGT FOREIGN KEY (SRVY_TRGT_ID) REFERENCES PLT_SRVY_TRGT(SRVY_TRGT_ID);
