CREATE TABLE PLT_CUST_INFO_CHG_DTL_EXPSN
(
	CUST_CHG_HSTRY_ID     BIGINT  NOT NULL ,
	ATTR_ID               BIGINT  NOT NULL ,
	ATTR_VL               VARCHAR(4000)  NULL 
);



CREATE UNIQUE INDEX PLT_CUST_INFO_CHG_DTL_EXPSN_PK ON PLT_CUST_INFO_CHG_DTL_EXPSN
(CUST_CHG_HSTRY_ID  ASC,ATTR_ID  ASC);



ALTER TABLE PLT_CUST_INFO_CHG_DTL_EXPSN
	ADD PRIMARY KEY (CUST_CHG_HSTRY_ID,ATTR_ID);



CREATE INDEX PLT_CUST_INFO_CHG_DTL_EXPSN_F1 ON PLT_CUST_INFO_CHG_DTL_EXPSN
(CUST_CHG_HSTRY_ID  ASC);



CREATE INDEX PLT_CUST_INFO_CHG_DTL_EXPSN_F2 ON PLT_CUST_INFO_CHG_DTL_EXPSN
(ATTR_ID  ASC);



CREATE TABLE PLT_CUST_INFO_CHG_HSTRY
(
	CUST_CHG_HSTRY_ID     BIGINT  NOT NULL ,
	CUST_ID               BIGINT  NULL ,
	CHG_REG_DT            VARCHAR(14)  NULL ,
	CHG_RGTR_ID           BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_CUST_INFO_CHG_HSTRY_PK ON PLT_CUST_INFO_CHG_HSTRY
(CUST_CHG_HSTRY_ID  ASC);



ALTER TABLE PLT_CUST_INFO_CHG_HSTRY
	ADD PRIMARY KEY (CUST_CHG_HSTRY_ID);



CREATE INDEX PLT_CUST_INFO_CHG_HSTRY_F1 ON PLT_CUST_INFO_CHG_HSTRY
(CUST_ID  ASC);



ALTER TABLE PLT_CUST_INFO_CHG_DTL_EXPSN
	ADD CONSTRAINT  R_CUST_INFO_CHG_DTL_EXPSN_2__C FOREIGN KEY (CUST_CHG_HSTRY_ID) REFERENCES PLT_CUST_INFO_CHG_HSTRY(CUST_CHG_HSTRY_ID);



ALTER TABLE PLT_CUST_INFO_CHG_DTL_EXPSN
	ADD CONSTRAINT  R_CUST_INFO_CHG_DTL_EXPSN_2__E FOREIGN KEY (ATTR_ID) REFERENCES PLT_EXPSN_ATTR(ATTR_ID);



ALTER TABLE PLT_CUST_INFO_CHG_HSTRY
	ADD CONSTRAINT  R_CUST_INFO_CHG_HSTRY_2__CUST_ FOREIGN KEY (CUST_ID) REFERENCES PLT_CUST(CUST_ID);



COMMENT ON TABLE PLT_CUST_INFO_CHG_DTL_EXPSN IS '고객_정보_변경_상세_확장';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_DTL_EXPSN.CUST_CHG_HSTRY_ID IS '고객_변경_이력_ID';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_DTL_EXPSN.ATTR_ID IS '속성_ID';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_DTL_EXPSN.ATTR_VL IS '속성_값';

COMMENT ON TABLE PLT_CUST_INFO_CHG_HSTRY IS '고객_정보_변경_이력';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_HSTRY.CUST_CHG_HSTRY_ID IS '고객_변경_이력_ID';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_HSTRY.CHG_REG_DT IS '변경_등록_일시';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_HSTRY.CHG_RGTR_ID IS '변경_등록자_ID';
COMMENT ON COLUMN PLT_CUST_INFO_CHG_HSTRY.CUST_ID IS '고객_ID';
