ALTER TABLE PLT_CUST ADD CUST_STTS_CD VARCHAR(60) NULL;
COMMENT ON COLUMN PLT_CUST.CUST_STTS_CD IS '고객_상태_코드';

ALTER TABLE PLT_CUST ADD DEL_YN CHAR(1)  NULL;
COMMENT ON COLUMN PLT_CUST.DEL_YN IS '삭제_여부';

ALTER TABLE PLT_CHT_CUST ADD SNDR_KEY BIGINT  NULL;
COMMENT ON COLUMN PLT_CHT_CUST.SNDR_KEY IS '발송자_키';

CREATE INDEX PLT_CHT_CUST_F2 ON PLT_CHT_CUST
(SNDR_KEY  ASC);


ALTER TABLE PLT_CHT_CUST
	ADD CONSTRAINT  R_CHT_CUST_2__CUSTCO_CHN_9c FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);
	
	

CREATE INDEX IDX_CUST_01 ON PLT_CUST
(CUSTCO_ID  ASC,CUST_PHN_NO  ASC);



CREATE INDEX IDX_CUST_02 ON PLT_CUST
(CUSTCO_ID  ASC,CUST_NM  ASC);



CREATE INDEX IDX_CUST_03 ON PLT_CUST
(CUSTCO_ID  ASC,CUST_ID  ASC);



CREATE INDEX IDX_CUST_04 ON PLT_CUST
(REG_DT  DESC);



CREATE INDEX IDX_CUST_05 ON PLT_CUST
(MDFCN_DT  DESC);


CREATE INDEX IDX_CUST_06 ON PLT_CUST USING gin(CUST_NM custco.gin_trgm_ops, CUST_PHN_NO custco.gin_trgm_ops);

CREATE INDEX IDX_CUST_07 ON PLT_CUST
(CUSTCO_ID  ASC,CUST_STTS_CD  ASC);