
CREATE TABLE PLT_SYS_LOG
(
	SYS_LOG_ID            BIGSERIAL  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	SE_CD                 VARCHAR(60)  NULL ,
	SE_NM                 VARCHAR(200)  NULL ,
	PARAM                 TEXT  NULL ,
	RSLT                  TEXT  NULL ,
	CNTN_MENU_CD          VARCHAR(320)  NULL ,
	CNTN_MENU_PATH        VARCHAR(200)  NULL ,
	CNTN_IP               VARCHAR(100)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_SYS_LOG_PK ON PLT_SYS_LOG
(SYS_LOG_ID  ASC);



ALTER TABLE PLT_SYS_LOG
	ADD PRIMARY KEY (SYS_LOG_ID);



COMMENT ON TABLE PLT_SYS_LOG IS '시스템_로그';
COMMENT ON COLUMN PLT_SYS_LOG.SYS_LOG_ID IS '시스템_로그_ID';
COMMENT ON COLUMN PLT_SYS_LOG.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_SYS_LOG.SE_CD IS '구분_코드';
COMMENT ON COLUMN PLT_SYS_LOG.PARAM IS '파라미터';
COMMENT ON COLUMN PLT_SYS_LOG.RSLT IS '결과';
COMMENT ON COLUMN PLT_SYS_LOG.CNTN_MENU_CD IS '접속_메뉴_코드';
COMMENT ON COLUMN PLT_SYS_LOG.CNTN_MENU_PATH IS '접속_메뉴_경로';
COMMENT ON COLUMN PLT_SYS_LOG.CNTN_IP IS '접속_IP';
COMMENT ON COLUMN PLT_SYS_LOG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_SYS_LOG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_SYS_LOG.SE_NM IS '구분_명';




