CREATE TABLE PLT_SHORT_KEY
(
	SHORT_KEY_ID          BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NULL ,
	SHORT_TYPE_CD         VARCHAR(60)  NULL ,
	LNK_ID                VARCHAR(200)  NULL ,
	ALT_KEY_YN            CHAR(1)  NULL ,
	SHIFT_KEY_YN          CHAR(1)  NULL ,
	KEY_CD                VARCHAR(60)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);

CREATE UNIQUE INDEX PLT_SHORT_KEY_PK ON PLT_SHORT_KEY
(SHORT_KEY_ID  ASC);

ALTER TABLE PLT_SHORT_KEY
	ADD PRIMARY KEY (SHORT_KEY_ID);

CREATE INDEX PLT_SHORT_KEY_F1 ON PLT_SHORT_KEY
(CUSTCO_ID  ASC);

ALTER TABLE PLT_SHORT_KEY
	ADD CONSTRAINT  R_SHORT_KEY_2__CUSTCO_40 FOREIGN KEY (CUSTCO_ID) REFERENCES PLT_CUSTCO(CUSTCO_ID);


COMMENT ON TABLE PLT_SHORT_KEY IS '단축_키';
COMMENT ON COLUMN PLT_SHORT_KEY.SHORT_KEY_ID IS '단축_키_ID';
COMMENT ON COLUMN PLT_SHORT_KEY.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_SHORT_KEY.SHORT_TYPE_CD IS '단축_유형_코드';
COMMENT ON COLUMN PLT_SHORT_KEY.LNK_ID IS '링크_ID';
COMMENT ON COLUMN PLT_SHORT_KEY.ALT_KEY_YN IS 'ALT_키_여부';
COMMENT ON COLUMN PLT_SHORT_KEY.SHIFT_KEY_YN IS 'SHIFT_키_여부';
COMMENT ON COLUMN PLT_SHORT_KEY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_SHORT_KEY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_SHORT_KEY.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_SHORT_KEY.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_SHORT_KEY.KEY_CD IS '키_코드';
