ALTER TABLE PLT_CUSTCO ADD USER_LGN_SMS_CERT_YN  CHAR(1)  NULL;
COMMENT ON COLUMN PLT_CUSTCO.USER_LGN_SMS_CERT_YN IS '사용자_로그인_SMS_인증_여부';

ALTER TABLE PLT_CUSTCO ADD SMS_CERT_EXPRY_HR  INT  NULL;
COMMENT ON COLUMN PLT_CUSTCO.SMS_CERT_EXPRY_HR IS 'SMS_인증_만료_시간';