CREATE TABLE PLT_USER_CERT_SMS_HSTRY
(
    CERT_SMS_HSTRY_ID     BIGINT  NOT NULL ,
    USER_ID               BIGINT  NULL ,
    CERT_NO_CRT_DT        VARCHAR(14)  NULL ,
    CERT_NO_EXPRY_DT      VARCHAR(14)  NULL ,
    CNTN_IP               VARCHAR(100)  NULL ,
    MTS_SNDNG_HSTRY_ID    BIGINT  NULL ,
    CERT_NO               VARCHAR(20)  NULL ,
    CERT_YN               CHAR(1)  NULL
);



CREATE UNIQUE INDEX PLT_USER_CERT_SMS_HSTRY_PK ON PLT_USER_CERT_SMS_HSTRY
    (CERT_SMS_HSTRY_ID  ASC);



ALTER TABLE PLT_USER_CERT_SMS_HSTRY
    ADD PRIMARY KEY (CERT_SMS_HSTRY_ID);



CREATE INDEX PLT_USER_CERT_SMS_HSTRY_F1 ON PLT_USER_CERT_SMS_HSTRY
    (USER_ID  ASC);



CREATE INDEX PLT_USER_CERT_SMS_HSTRY_F2 ON PLT_USER_CERT_SMS_HSTRY
    (MTS_SNDNG_HSTRY_ID  ASC);



ALTER TABLE PLT_USER_CERT_SMS_HSTRY
    ADD CONSTRAINT  R_USER_CERT_SMS_HSTRY_2__USER_ FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_USER_CERT_SMS_HSTRY
    ADD CONSTRAINT  R_USER_CERT_SMS_HSTRY_2__MTS_S FOREIGN KEY (MTS_SNDNG_HSTRY_ID) REFERENCES PLT_MTS_SNDNG_HSTRY(MTS_SNDNG_HSTRY_ID);



COMMENT ON TABLE PLT_USER_CERT_SMS_HSTRY IS '사용자_인증_SMS_이력';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CERT_SMS_HSTRY_ID IS '인증_SMS_이력_ID';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CERT_NO_CRT_DT IS '인증_번호_생성_일시';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CNTN_IP IS '접속_IP';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CERT_NO_EXPRY_DT IS '인증_번호_만료_일시';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.MTS_SNDNG_HSTRY_ID IS 'MTS_발송_이력_ID';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CERT_NO IS '인증_번호';
COMMENT ON COLUMN PLT_USER_CERT_SMS_HSTRY.CERT_YN IS '인증_여부';


