ALTER TABLE PLT_CUST_DTL_EXPSN ALTER COLUMN ATTR_VL TYPE TEXT;

ALTER TABLE PLT_CUST_INFO_CHG_DTL_EXPSN ALTER COLUMN ATTR_VL TYPE TEXT;

ALTER TABLE PLT_PHN_CUTT_DTL_EXPSN ALTER COLUMN ATTR_VL TYPE TEXT;

ALTER TABLE PLT_PHN_CUTT_CHG_DSCTN ALTER COLUMN ATTR_VL TYPE TEXT;

ALTER TABLE PLT_OBD_CPI_CUST_DTL ALTER COLUMN ATTR_VL TYPE TEXT;

ALTER TABLE PLT_PHN_CUTT_DTL_CN ALTER COLUMN CUTT_CN TYPE TEXT;

ALTER TABLE PLT_PHN_CUTT_CHG_CN ALTER COLUMN CUTT_CN TYPE TEXT;