
CREATE TABLE PLT_CHT_CUTT_BBS
(
	CHT_CUTT_BBS_ID       BIGINT  NOT NULL ,
	SNDR_KEY              BIGINT  NULL ,
	CHT_CUTT_ID           BIGINT  NULL ,
	RCPTN_DSPTCH_CD       VARCHAR(60)  NULL ,
	PST_ID                VARCHAR(60)  NULL ,
	WRTR_ID               VARCHAR(60)  NULL ,
	WRTR_NM               VARCHAR(100)  NULL ,
	TTL                   VARCHAR(300)  NULL ,
	CN                    TEXT  NULL ,
	WRT_DT                VARCHAR(14)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_CUTT_BBS_PK ON PLT_CHT_CUTT_BBS
(CHT_CUTT_BBS_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_BBS
	ADD PRIMARY KEY (CHT_CUTT_BBS_ID);



CREATE INDEX IDX_CHT_CUTT_BBS_01 ON PLT_CHT_CUTT_BBS
(RCPTN_DSPTCH_CD  ASC);



CREATE INDEX IDX_CHT_CUTT_BBS_02 ON PLT_CHT_CUTT_BBS
(PST_ID  ASC);



CREATE INDEX IDX_CHT_CUTT_BBS_03 ON PLT_CHT_CUTT_BBS
(WRT_DT  ASC);



CREATE INDEX PLT_CHT_CUTT_BBS_F1 ON PLT_CHT_CUTT_BBS
(SNDR_KEY  ASC);



CREATE INDEX PLT_CHT_CUTT_BBS_F2 ON PLT_CHT_CUTT_BBS
(CHT_CUTT_ID  ASC);



CREATE TABLE PLT_CHT_CUTT_EML
(
	CHT_CUTT_EML_ID       BIGINT  NOT NULL ,
	SNDR_KEY              BIGINT  NULL ,
	CHT_CUTT_ID           BIGINT  NULL ,
	SRVR                  VARCHAR(100)  NULL ,
	MSG_ID                VARCHAR(200)  NULL ,
	RCPTN_DT              VARCHAR(14)  NULL ,
	SNDR_EML              VARCHAR(100)  NULL ,
	RCVR_EML              VARCHAR(1000)  NULL ,
	RFRNC_EML             VARCHAR(1000)  NULL ,
	HID_RFRNC_EML         VARCHAR(1000)  NULL ,
	TTL                   VARCHAR(300)  NULL ,
	CN                    TEXT  NULL ,
	FILE_GROUP_KEY        VARCHAR(90)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_CUTT_EML_PK ON PLT_CHT_CUTT_EML
(CHT_CUTT_EML_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_EML
	ADD PRIMARY KEY (CHT_CUTT_EML_ID);



CREATE INDEX IDX_CHT_CUTT_EML_01 ON PLT_CHT_CUTT_EML
(MSG_ID  ASC);



CREATE INDEX IDX_CHT_CUTT_EML_02 ON PLT_CHT_CUTT_EML
(RCPTN_DT  ASC);



CREATE INDEX PLT_CHT_CUTT_EML_F1 ON PLT_CHT_CUTT_EML
(SNDR_KEY  ASC);



CREATE INDEX PLT_CHT_CUTT_EML_F2 ON PLT_CHT_CUTT_EML
(CHT_CUTT_ID  ASC);



CREATE TABLE PLT_CUSTCO_CHN_BBS_STNG
(
	SNDR_KEY              BIGINT  NOT NULL ,
	INQ_API_ID            BIGINT  NOT NULL ,
	REG_API_ID            BIGINT  NOT NULL ,
	RPRS_REG_ID           VARCHAR(60)  NULL ,
	CLCT_RPTT             INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CUSTCO_CHN_BBS_STNG_PK ON PLT_CUSTCO_CHN_BBS_STNG
(SNDR_KEY  ASC);



ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG
	ADD PRIMARY KEY (SNDR_KEY);



CREATE INDEX PLT_CUSTCO_CHN_BBS_STNG_F1 ON PLT_CUSTCO_CHN_BBS_STNG
(SNDR_KEY  ASC);



CREATE TABLE PLT_CUSTCO_CHN_EML_STNG
(
	SNDR_KEY              BIGINT  NOT NULL ,
	SRVR                  VARCHAR(100)  NULL ,
	PORT                  INT  NULL ,
	ACNT                  VARCHAR(100)  NULL ,
	PSWD                  VARCHAR(100)  NULL ,
	PROTOCOL_CD           VARCHAR(60)  NULL ,
	SNDR_EML              VARCHAR(60)  NULL ,
	SNDR_NM               VARCHAR(100)  NULL ,
	CLCT_RPTT             INT  NULL ,
	SMTP_SRVR             VARCHAR(100)  NULL ,
	SMTP_PORT             INT  NULL ,
	SMTP_RPRS_YN          CHAR(1) NULL,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL
);



CREATE UNIQUE INDEX PLT_CUSTCO_CHN_EML_STNG_PK ON PLT_CUSTCO_CHN_EML_STNG
(SNDR_KEY  ASC);



ALTER TABLE PLT_CUSTCO_CHN_EML_STNG
	ADD PRIMARY KEY (SNDR_KEY);



CREATE INDEX PLT_CUSTCO_CHN_EML_STNG_F1 ON PLT_CUSTCO_CHN_EML_STNG
(SNDR_KEY  ASC);



CREATE TABLE PLT_EML_SNDNG_HSTRY
(
	EML_SNDNG_ID          BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NULL ,
	SNDR_EML              VARCHAR(100)  NULL ,
	RCVR_EML              VARCHAR(1000)  NULL ,
	RFRNC_EML             VARCHAR(1000)  NULL ,
	HID_RFRNC_EML         VARCHAR(1000)  NULL ,
	TTL                   VARCHAR(300)  NULL ,
	CN                    TEXT  NULL ,
	FILE_GROUP_KEY        VARCHAR(90)  NULL ,
	SNDNG_TYPE_CD         VARCHAR(60)  NULL ,
	RSVT_DT               VARCHAR(14)  NULL ,
	SNDNG_DT              VARCHAR(14)  NULL ,
	RSLT_CD               VARCHAR(60)  NULL ,
	RSLT_MSG              VARCHAR(300)  NULL ,
	CUST_ID               BIGINT  NULL ,
	CHT_CUTT_ID           BIGINT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_EML_SNDNG_HSTRY_PK ON PLT_EML_SNDNG_HSTRY
(EML_SNDNG_ID  ASC);



ALTER TABLE PLT_EML_SNDNG_HSTRY
	ADD PRIMARY KEY (EML_SNDNG_ID);



CREATE INDEX IDX_EML_SNDNG_HSTRY_01 ON PLT_EML_SNDNG_HSTRY
(SNDNG_TYPE_CD  ASC);



CREATE INDEX IDX_EML_SNDNG_HSTRY_02 ON PLT_EML_SNDNG_HSTRY
(RSVT_DT  ASC);



CREATE INDEX IDX_EML_SNDNG_HSTRY_03 ON PLT_EML_SNDNG_HSTRY
(RSLT_CD  ASC);



CREATE INDEX IDX_EML_SNDNG_HSTRY_04 ON PLT_EML_SNDNG_HSTRY
(REG_DT  ASC);



CREATE INDEX PLT_EML_SNDNG_HSTRY_F1 ON PLT_EML_SNDNG_HSTRY
(CUSTCO_ID  ASC);



CREATE INDEX PLT_EML_SNDNG_HSTRY_F2 ON PLT_EML_SNDNG_HSTRY
(CUST_ID  ASC);



CREATE INDEX PLT_EML_SNDNG_HSTRY_F3 ON PLT_EML_SNDNG_HSTRY
(CHT_CUTT_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_BBS
	ADD CONSTRAINT  R_CHT_CUTT_BBS_2__CUSTCO_CHN_9 FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



ALTER TABLE PLT_CHT_CUTT_BBS
	ADD CONSTRAINT  R_CHT_CUTT_BBS_2__CHT_CUTT_e7 FOREIGN KEY (CHT_CUTT_ID) REFERENCES PLT_CHT_CUTT(CHT_CUTT_ID);



ALTER TABLE PLT_CHT_CUTT_EML
	ADD CONSTRAINT  R_CHT_CUTT_EML_2__CUSTCO_CHN_1 FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



ALTER TABLE PLT_CHT_CUTT_EML
	ADD CONSTRAINT  R_CHT_CUTT_EML_2__CHT_CUTT_4a FOREIGN KEY (CHT_CUTT_ID) REFERENCES PLT_CHT_CUTT(CHT_CUTT_ID);



ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG
	ADD CONSTRAINT  R_CUSTCO_CHN_BBS_STNG_2__CUSTC FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



ALTER TABLE PLT_CUSTCO_CHN_EML_STNG
	ADD CONSTRAINT  R_CUSTCO_CHN_EML_STNG_2__CUSTC FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



ALTER TABLE PLT_EML_SNDNG_HSTRY
	ADD CONSTRAINT  R_EML_SNDNG_HSTRY_2__CUSTCO_cb FOREIGN KEY (CUSTCO_ID) REFERENCES PLT_CUSTCO(CUSTCO_ID);



ALTER TABLE PLT_EML_SNDNG_HSTRY
	ADD CONSTRAINT  R_EML_SNDNG_HSTRY_2__CUST_de FOREIGN KEY (CUST_ID) REFERENCES PLT_CUST(CUST_ID);



ALTER TABLE PLT_EML_SNDNG_HSTRY
	ADD CONSTRAINT  R_EML_SNDNG_HSTRY_2__CHT_CUTT_ FOREIGN KEY (CHT_CUTT_ID) REFERENCES PLT_CHT_CUTT(CHT_CUTT_ID);



COMMENT ON TABLE PLT_CHT_CUTT_BBS IS '채팅_상담_게시판';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.CHT_CUTT_BBS_ID IS '채팅_상담_게시판_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.CHT_CUTT_ID IS '채팅_상담_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.RCPTN_DSPTCH_CD IS '수신_발신_코드';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.PST_ID IS '게시물_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.WRTR_ID IS '작성자_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.TTL IS '제목';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.CN IS '내용';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.WRTR_NM IS '작성자_명';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.WRT_DT IS '작성_일시';

COMMENT ON TABLE PLT_CHT_CUTT_EML IS '채팅_상담_이메일';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.CHT_CUTT_EML_ID IS '채팅_상담_이메일_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.CHT_CUTT_ID IS '채팅_상담_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.SRVR IS '서버';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.MSG_ID IS '메시지_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.RCPTN_DT IS '수신_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.SNDR_EML IS '발송자_이메일';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.RCVR_EML IS '수신자_이메일';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.RFRNC_EML IS '참조_이메일';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.HID_RFRNC_EML IS '숨김_참조_이메일';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.TTL IS '제목';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.CN IS '내용';
COMMENT ON COLUMN PLT_CHT_CUTT_EML.FILE_GROUP_KEY IS '파일_그룹_키';

COMMENT ON TABLE PLT_CUSTCO_CHN_BBS_STNG IS '고객사_채널_게시판_설정';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.INQ_API_ID IS '조회_API_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.REG_API_ID IS '등록_API_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.CLCT_RPTT IS '수집_주기';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.RPRS_REG_ID IS '대표_등록_ID';

COMMENT ON TABLE PLT_CUSTCO_CHN_EML_STNG IS '고객사_채널_이메일_설정';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SRVR IS '서버';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.PORT IS 'PORT';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.ACNT IS '계정';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.PSWD IS '비밀번호';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.PROTOCOL_CD IS 'PROTOCOL_코드';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SNDR_EML IS '발송자_이메일';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.CLCT_RPTT IS '수집_주기';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SMTP_SRVR IS 'SMTP_서버';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SMTP_PORT IS 'SMTP_PORT';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SMTP_RPRS_YN IS 'SMTP_대표_여부';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CUSTCO_CHN_EML_STNG.SNDR_NM IS '발송자_명';

COMMENT ON TABLE PLT_EML_SNDNG_HSTRY IS '이메일_발송_이력';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.EML_SNDNG_ID IS '이메일_발송_ID';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.SNDR_EML IS '발송자_이메일';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RCVR_EML IS '수신자_이메일';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RFRNC_EML IS '참조_이메일';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.HID_RFRNC_EML IS '숨김_참조_이메일';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.TTL IS '제목';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.CN IS '내용';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.FILE_GROUP_KEY IS '파일_그룹_키';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.SNDNG_TYPE_CD IS '발송_유형_코드';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RSVT_DT IS '예약_일시';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.SNDNG_DT IS '발송_일시';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RSLT_CD IS '결과_코드';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RSLT_MSG IS '결과_메시지';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.CUST_ID IS '고객_ID';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_EML_SNDNG_HSTRY.CHT_CUTT_ID IS '채팅_상담_ID';




CREATE TABLE PLT_CLCT_JOB_HSTRY
(
	CLCT_JOB_HSTRY_ID     BIGSERIAL  NOT NULL ,
	JOB_MNG_ID            BIGINT  NULL ,
	JOB_BGNG_DT           VARCHAR(14)  NULL ,
	JOB_END_DT            VARCHAR(14)  NULL ,
	AFTR_JOB_BGNG_DT      VARCHAR(14)  NULL ,
	JOB_HR                NUMERIC(5,2)  NULL ,
	JOB_SCS_YN            CHAR(1)  NULL ,
	JOB_RSLT_MSG          VARCHAR(200)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_CLCT_JOB_HSTRY_PK ON PLT_CLCT_JOB_HSTRY
(CLCT_JOB_HSTRY_ID  ASC);



ALTER TABLE PLT_CLCT_JOB_HSTRY
	ADD PRIMARY KEY (CLCT_JOB_HSTRY_ID);



CREATE INDEX PLT_CLCT_JOB_HSTRY_F1 ON PLT_CLCT_JOB_HSTRY
(JOB_MNG_ID  ASC);



CREATE TABLE PLT_CLCT_JOB_MNG
(
	JOB_MNG_ID            BIGINT  NOT NULL ,
	CLCT_JOB_CD           VARCHAR(14)  NOT NULL ,
	SNDR_KEY              BIGINT  NULL ,
	JOB_NM                VARCHAR(300)  NULL ,
	STTS_CD               VARCHAR(60)  NULL ,
	JOB_BGNG_DT           VARCHAR(14)  NULL ,
	JOB_END_DT            VARCHAR(14)  NULL ,
	AFTR_JOB_BGNG_DT      VARCHAR(14)  NULL ,
	JOB_HR                NUMERIC(5,2)  NULL ,
	FAIL_CNT              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CLCT_JOB_MNG_PK ON PLT_CLCT_JOB_MNG
(JOB_MNG_ID  ASC);



ALTER TABLE PLT_CLCT_JOB_MNG
	ADD PRIMARY KEY (JOB_MNG_ID);



CREATE INDEX IDX_CLCT_JOB_MNG_01 ON PLT_CLCT_JOB_MNG
(CLCT_JOB_CD  ASC,SNDR_KEY  ASC);



CREATE INDEX IDX_CLCT_JOB_MNG_02 ON PLT_CLCT_JOB_MNG
(STTS_CD  ASC);



CREATE INDEX PLT_CLCT_JOB_MNG_F1 ON PLT_CLCT_JOB_MNG
(SNDR_KEY  ASC);



ALTER TABLE PLT_CLCT_JOB_HSTRY
	ADD CONSTRAINT  R_CLCT_JOB_HSTRY_2__CLCT_JOB_M FOREIGN KEY (JOB_MNG_ID) REFERENCES PLT_CLCT_JOB_MNG(JOB_MNG_ID);



ALTER TABLE PLT_CLCT_JOB_MNG
	ADD CONSTRAINT  R_CLCT_JOB_MNG_2__CUSTCO_CHN_7 FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



COMMENT ON TABLE PLT_CLCT_JOB_HSTRY IS '수집_작업_이력';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.CLCT_JOB_HSTRY_ID IS '수집_작업_이력_ID';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_BGNG_DT IS '작업_시작_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_END_DT IS '작업_종료_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.AFTR_JOB_BGNG_DT IS '이후_작업_시작_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_HR IS '작업_시간';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_MNG_ID IS '작업_관리_ID';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_SCS_YN IS '작업_성공_여부';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_HSTRY.JOB_RSLT_MSG IS '작업_결과_메시지';

COMMENT ON TABLE PLT_CLCT_JOB_MNG IS '수집_작업_관리';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.JOB_MNG_ID IS '작업_관리_ID';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.CLCT_JOB_CD IS '수집_작업_코드';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.JOB_NM IS '작업_명';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.STTS_CD IS '상태_코드';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.JOB_BGNG_DT IS '작업_시작_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.JOB_END_DT IS '작업_종료_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.AFTR_JOB_BGNG_DT IS '이후_작업_시작_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.JOB_HR IS '작업_시간';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.FAIL_CNT IS '실패_수';








--공통코드 추가
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'CHNL_CL', 'NTT', custco_id, '네이버톡톡', '네이버톡톡', 'CHAT', 'Y', 'Y', 'N', 3, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'CHNL_CL', 'BBS', custco_id, '게시판', '게시판', NULL, 'Y', 'Y', 'N', 4, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'CHNL_CL', 'EMAIL', custco_id, '이메일', '이메일', NULL, 'Y', 'Y', 'N', 5, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;

INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt) 
select '*', 'EMAIL_PROTOCOL_TP', custco_id, '이메일 프로토콜 유형', '이메일 프로토콜 유형', NULL, 'Y', 'Y', 'N', 109, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt) 
select 'EMAIL_PROTOCOL_TP', 'imaps', custco_id, 'imaps', 'imap Secure', NULL, 'Y', 'Y', 'N', 1, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco  ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt) 
select 'EMAIL_PROTOCOL_TP', 'imap', custco_id, 'imap', 'imap', NULL, 'Y', 'Y', 'N', 2, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;

INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select '*', 'JOB_MNG_ST', custco_id, '수집 작업 관리 상태', '수집 작업 관리 상태', NULL, 'Y', 'Y', 'N', 112, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'JOB_MNG_ST', 'WAIT', custco_id, '대기', '대기', NULL, 'Y', 'Y', 'N', 1, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'JOB_MNG_ST', 'RUN', custco_id, '실행중', '실행중', NULL, 'Y', 'Y', 'N', 2, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO plt_comm_cd (group_cd_id, cd_id, custco_id, cd_nm, cd_expln, cd_vl, sys_cd_yn, use_yn, del_yn, sort_ord, rgtr_id, reg_dt, mdfr_id, mdfcn_dt)
select 'JOB_MNG_ST', 'STOP', custco_id, '사용중지', '사용중지', NULL, 'Y', 'Y', 'N', 3, 2, to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;

