ALTER TABLE PLT_STATS_CHT_CUTT_DTL ADD CUTT_SE_CD            VARCHAR(60)  NULL;
ALTER TABLE PLT_STATS_CHT_CUTT_DTL ADD ALTMNT_HR             INT  NULL;
ALTER TABLE PLT_STATS_CHT_CUTT_DTL ADD AFTPRCS_HR            INT  NULL;
ALTER TABLE PLT_STATS_CHT_CUTT_DTL ADD PRCS_HR               INT  NULL;
ALTER TABLE PLT_STATS_CHT_CUTT_DTL ADD RDY_HR                INT  NULL;

COMMENT ON COLUMN PLT_STATS_CHT_CUTT_DTL.CUTT_SE_CD IS '상담_구분_코드';
COMMENT ON COLUMN PLT_STATS_CHT_CUTT_DTL.ALTMNT_HR IS '배정_시간';
COMMENT ON COLUMN PLT_STATS_CHT_CUTT_DTL.AFTPRCS_HR IS '후처리_시간';
COMMENT ON COLUMN PLT_STATS_CHT_CUTT_DTL.PRCS_HR IS '처리_시간';
COMMENT ON COLUMN PLT_STATS_CHT_CUTT_DTL.RDY_HR IS '대기_시간';
