ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG ADD IF NOT EXISTS LKAG_MST_ID BIGINT NULL;
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.LKAG_MST_ID IS '연동_마스터_ID';

ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG ADD IF NOT EXISTS BBS_INQRY_TYPE_CD VARCHAR(60) NULL;
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.BBS_INQRY_TYPE_CD IS '게시판_문의_유형_코드';

INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select '*', 'BBS_INQ_TP', custco_id, '게시판 문의 유형', '게시판 문의 유형', 'CHAT', 'Y', 'Y', 'N', '120', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'BBS_INQ_TP', 'INQRY_CUST', custco_id, '고객문의', '고객문의', NULL, 'Y', 'Y', 'N', '1', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'BBS_INQ_TP', 'INQRY_GDS', custco_id, '상품문의', '상품문의', NULL, 'Y', 'Y', 'N', '2', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;

INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select '*', 'PST_INQ_TP', custco_id, '게시물 문의 유형', '게시물 문의 유형', NULL, 'Y', 'Y', 'N', '121', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'PRODUCT', custco_id, '상품', '상품', NULL, 'Y', 'Y', 'N', '1', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'DELIVERY', custco_id, '배송', '배송', NULL, 'Y', 'Y', 'N', '2', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'RETURN', custco_id, '반품', '반품', NULL, 'Y', 'Y', 'N', '3', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'EXCHANGE', custco_id, '교환', '교환', NULL, 'Y', 'Y', 'N', '4', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'CANCEL', custco_id, '취소 및 환불', '취소 및 환불', NULL, 'Y', 'Y', 'N', '5', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'PST_INQ_TP', 'ETC', custco_id, '기타', '기타', NULL, 'Y', 'Y', 'N', '6', '2', to_char(now(),'yyyymmddhh24miss'), null, null from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;




CREATE TABLE PLT_ECMRC_INQRY_BBS
(
	SNDR_KEY              BIGINT  NULL ,
	ECMRC_INQRY_BBS_ID    BIGINT  NOT NULL ,
	INQRY_NO              VARCHAR(100)  NULL ,
	INQRY_TYPE            VARCHAR(60)  NULL ,
	ORDR_YN               CHAR(1)  NULL ,
	ORDR_NO               VARCHAR(256)  NULL ,
	ORDR_DT               VARCHAR(14)  NULL ,
	GDS_NO                VARCHAR(256)  NULL ,
	GDS_NM                VARCHAR(200)  NULL ,
	INQRY_TTL             VARCHAR(200)  NULL ,
	INQRY_CN              TEXT  NULL ,
	ULD_IMG_URL           VARCHAR(2000)  NULL ,
	WRTR_ID               VARCHAR(100)  NULL ,
	WRTR_NM               VARCHAR(100)  NULL ,
	WRT_DT                VARCHAR(14)  NULL ,
	REG_DT                VARCHAR(14)  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_ECMRC_INQRY_BBS_PK ON PLT_ECMRC_INQRY_BBS
(ECMRC_INQRY_BBS_ID  ASC);



ALTER TABLE PLT_ECMRC_INQRY_BBS
	ADD PRIMARY KEY (ECMRC_INQRY_BBS_ID);



CREATE INDEX PLT_ECMRC_INQRY_BBS_F1 ON PLT_ECMRC_INQRY_BBS
(SNDR_KEY  ASC);



CREATE TABLE PLT_ECMRC_INQRY_BBS_ANSWR
(
	ECMRC_INQRY_BBS_ANSWR_ID  BIGINT  NOT NULL ,
	ECMRC_INQRY_BBS_ID    BIGINT  NULL ,
	ANSWR_CN              TEXT  NULL ,
	ANSWR_DT              VARCHAR(14)  NULL ,
	ANSWR_ID              BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_ECMRC_INQRY_BBS_ANSWR_PK ON PLT_ECMRC_INQRY_BBS_ANSWR
(ECMRC_INQRY_BBS_ANSWR_ID  ASC);



ALTER TABLE PLT_ECMRC_INQRY_BBS_ANSWR
	ADD PRIMARY KEY (ECMRC_INQRY_BBS_ANSWR_ID);



CREATE INDEX PLT_ECMRC_INQRY_BBS_ANSWR_F1 ON PLT_ECMRC_INQRY_BBS_ANSWR
(ECMRC_INQRY_BBS_ID  ASC);



ALTER TABLE PLT_ECMRC_INQRY_BBS
	ADD CONSTRAINT  R_ECMRC_INQRY_BBS_2__CUSTCO_CH FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN(SNDR_KEY);



ALTER TABLE PLT_ECMRC_INQRY_BBS_ANSWR
	ADD CONSTRAINT  R_ECMRC_INQRY_BBS_ANSWR_2__ECM FOREIGN KEY (ECMRC_INQRY_BBS_ID) REFERENCES PLT_ECMRC_INQRY_BBS(ECMRC_INQRY_BBS_ID);



COMMENT ON TABLE PLT_ECMRC_INQRY_BBS IS '전자상거래_문의_게시판';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ECMRC_INQRY_BBS_ID IS '전자상거래_문의_게시판_ID';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.INQRY_NO IS '문의_번호';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.INQRY_TYPE IS '문의_유형';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ORDR_YN IS '주문_여부';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ORDR_NO IS '주문_번호';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ORDR_DT IS '주문_일시';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.GDS_NO IS '상품_번호';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.GDS_NM IS '상품_명';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.INQRY_TTL IS '문의_제목';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.INQRY_CN IS '문의_내용';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.WRTR_ID IS '작성자_ID';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.WRTR_NM IS '작성자_명';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ULD_IMG_URL IS '업로드_이미지_URL';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.WRT_DT IS '작성_일시';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.SNDR_KEY IS '발송자_키';

COMMENT ON TABLE PLT_ECMRC_INQRY_BBS_ANSWR IS '전자상거래_문의_게시판_답변';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS_ANSWR.ECMRC_INQRY_BBS_ANSWR_ID IS '전자상거래_문의_게시판_답변_ID';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS_ANSWR.ECMRC_INQRY_BBS_ID IS '전자상거래_문의_게시판_ID';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS_ANSWR.ANSWR_CN IS '답변_내용';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS_ANSWR.ANSWR_DT IS '답변_일시';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS_ANSWR.ANSWR_ID IS '답변자_ID';