
CREATE TABLE PLT_LAYOUT
(
	LAYOUT_ID             BIGINT  NOT NULL ,
	LAYOUT_CLSF_ID        BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NULL ,
	LAYOUT_NM             VARCHAR(100)  NULL ,
	LAYOUT_TYPE_CD        VARCHAR(60)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_PK ON PLT_LAYOUT
(LAYOUT_ID  ASC);



ALTER TABLE PLT_LAYOUT
	ADD PRIMARY KEY (LAYOUT_ID);



CREATE INDEX PLT_LAYOUT_F3 ON PLT_LAYOUT
(CUSTCO_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST
(
	LIST_ID               BIGINT  NOT NULL ,
	TAB_ID                BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_PK ON PLT_LAYOUT_LIST
(LIST_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST
	ADD PRIMARY KEY (LIST_ID);



CREATE INDEX PLT_LAYOUT_LIST_F1 ON PLT_LAYOUT_LIST
(TAB_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_DWN_GROUP
(
	LIST_DWN_GROUP_ID     BIGINT  NOT NULL ,
	LIST_ID               BIGINT  NULL ,
	LIST_DWN_GROUP_TTL    VARCHAR(100)  NULL ,
	WD_SZ                 INT  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_DWN_GROUP_PK ON PLT_LAYOUT_LIST_DWN_GROUP
(LIST_DWN_GROUP_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_DWN_GROUP
	ADD PRIMARY KEY (LIST_DWN_GROUP_ID);



CREATE INDEX PLT_LAYOUT_LIST_DWN_GROUP_F1 ON PLT_LAYOUT_LIST_DWN_GROUP
(LIST_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_DWN_GROUP_DTL
(
	LIST_DWN_GROUP_DTL_ID  BIGINT  NOT NULL ,
	LIST_DWN_GROUP_ID     BIGINT  NULL ,
	RSPNS_ARTCL_ID        BIGINT  NOT NULL ,
	LABEL_NM              VARCHAR(100)  NULL ,
	EPSZ_YN               CHAR(1)  NULL ,
	COLOR_CD              VARCHAR(20)  NULL ,
	RSPNS_EPSZ_YN         CHAR(1)  NULL ,
	RSPNS_COLOR_CD        VARCHAR(20)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_DWN_GROUP_DTL1 ON PLT_LAYOUT_LIST_DWN_GROUP_DTL
(LIST_DWN_GROUP_DTL_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_DWN_GROUP_DTL
	ADD PRIMARY KEY (LIST_DWN_GROUP_DTL_ID);



CREATE INDEX PLT_LAYOUT_LIST_DWN_GROUP_DTL2 ON PLT_LAYOUT_LIST_DWN_GROUP_DTL
(LIST_DWN_GROUP_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_GROUP
(
	LIST_GROUP_ID         BIGINT  NOT NULL ,
	LIST_ID               BIGINT  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_GROUP_PK ON PLT_LAYOUT_LIST_GROUP
(LIST_GROUP_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_GROUP
	ADD PRIMARY KEY (LIST_GROUP_ID);



CREATE INDEX PLT_LAYOUT_LIST_GROUP_F1 ON PLT_LAYOUT_LIST_GROUP
(LIST_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_GROUP_DTL
(
	LIST_GROUP_DTL_ID     BIGINT  NOT NULL ,
	LIST_GROUP_ID         BIGINT  NULL ,
	RSPNS_ARTCL_ID        BIGINT  NOT NULL ,
	LABEL_NM              VARCHAR(100)  NULL ,
	EPSZ_YN               CHAR(1)  NULL ,
	COLOR_CD              VARCHAR(20)  NULL ,
	RSPNS_EPSZ_YN         CHAR(1)  NULL ,
	RSPNS_COLOR_CD        VARCHAR(20)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_GROUP_DTL_PK ON PLT_LAYOUT_LIST_GROUP_DTL
(LIST_GROUP_DTL_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_GROUP_DTL
	ADD PRIMARY KEY (LIST_GROUP_DTL_ID);



CREATE INDEX PLT_LAYOUT_LIST_GROUP_DTL_F3 ON PLT_LAYOUT_LIST_GROUP_DTL
(LIST_GROUP_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_SRCH
(
	LIST_ID               BIGINT  NOT NULL ,
	PARAM_ARTCL_ID        BIGINT  NOT NULL ,
	GROUP_CD_ID           VARCHAR(60)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_SRCH_PK ON PLT_LAYOUT_LIST_SRCH
(LIST_ID  ASC,PARAM_ARTCL_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_SRCH
	ADD PRIMARY KEY (LIST_ID,PARAM_ARTCL_ID);



CREATE INDEX PLT_LAYOUT_LIST_SRCH_F5 ON PLT_LAYOUT_LIST_SRCH
(LIST_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_STTS
(
	LIST_ID               BIGINT  NOT NULL ,
	RSPNS_ARTCL_ID        BIGINT  NOT NULL ,
	STTS_NM               VARCHAR(100)  NULL ,
	EPSZ_YN               CHAR(1)  NULL ,
	COLOR_CD              VARCHAR(20)  NULL ,
	SORT_MTHD_CD          VARCHAR(60)  NULL ,
	BG_COLOR_CD           VARCHAR(20)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_STTS_PK ON PLT_LAYOUT_LIST_STTS
(LIST_ID  ASC,RSPNS_ARTCL_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_STTS
	ADD PRIMARY KEY (LIST_ID,RSPNS_ARTCL_ID);



CREATE INDEX PLT_LAYOUT_LIST_STTS_F1 ON PLT_LAYOUT_LIST_STTS
(LIST_ID  ASC);



CREATE TABLE PLT_LAYOUT_LIST_THUMNAIL
(
	LIST_ID               BIGINT  NOT NULL ,
	RSPNS_ARTCL_ID        BIGINT  NOT NULL ,
	WD_SZ                 INT  NULL ,
	HT_SZ                 INT  NULL ,
	OUTLN_COLOR_CD        VARCHAR(20)  NULL ,
	OUTLN_TYPE_CD         VARCHAR(60)  NULL ,
	LN_PX                 VARCHAR(60)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_LIST_THUMNAIL_PK ON PLT_LAYOUT_LIST_THUMNAIL
(LIST_ID  ASC,RSPNS_ARTCL_ID  ASC);



ALTER TABLE PLT_LAYOUT_LIST_THUMNAIL
	ADD PRIMARY KEY (LIST_ID,RSPNS_ARTCL_ID);



CREATE INDEX PLT_LAYOUT_LIST_THUMNAIL_F3 ON PLT_LAYOUT_LIST_THUMNAIL
(LIST_ID  ASC);



CREATE TABLE PLT_LAYOUT_TAB
(
	TAB_ID                BIGINT  NOT NULL ,
	LAYOUT_ID             BIGINT  NULL ,
	RSPNS_ARTCL_ID        BIGINT  NULL ,
	TAB_NM                VARCHAR(100)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_TAB_PK ON PLT_LAYOUT_TAB
(TAB_ID  ASC);



ALTER TABLE PLT_LAYOUT_TAB
	ADD PRIMARY KEY (TAB_ID);



CREATE INDEX PLT_LAYOUT_TAB_F1 ON PLT_LAYOUT_TAB
(LAYOUT_ID  ASC);



ALTER TABLE PLT_LAYOUT
	ADD CONSTRAINT  R_LAYOUT_2__CUSTCO_d1 FOREIGN KEY (CUSTCO_ID) REFERENCES PLT_CUSTCO(CUSTCO_ID);



ALTER TABLE PLT_LAYOUT_LIST
	ADD CONSTRAINT  R_LAYOUT_LIST_2__LAYOUT_TAB_56 FOREIGN KEY (TAB_ID) REFERENCES PLT_LAYOUT_TAB(TAB_ID);



ALTER TABLE PLT_LAYOUT_LIST_DWN_GROUP
	ADD CONSTRAINT  R_LAYOUT_LIST_DWN_GROUP_2__LAY FOREIGN KEY (LIST_ID) REFERENCES PLT_LAYOUT_LIST(LIST_ID);



ALTER TABLE PLT_LAYOUT_LIST_DWN_GROUP_DTL
	ADD CONSTRAINT  R_LAYOUT_LIST_DWN_GROUP_DTL_4_ FOREIGN KEY (LIST_DWN_GROUP_ID) REFERENCES PLT_LAYOUT_LIST_DWN_GROUP(LIST_DWN_GROUP_ID);



ALTER TABLE PLT_LAYOUT_LIST_GROUP
	ADD CONSTRAINT  R_LAYOUT_LIST_GROUP_2__LAYOUT_ FOREIGN KEY (LIST_ID) REFERENCES PLT_LAYOUT_LIST(LIST_ID);



ALTER TABLE PLT_LAYOUT_LIST_GROUP_DTL
	ADD CONSTRAINT  R_LAYOUT_LIST_GROUP_DTL_2__LAY FOREIGN KEY (LIST_GROUP_ID) REFERENCES PLT_LAYOUT_LIST_GROUP(LIST_GROUP_ID);



ALTER TABLE PLT_LAYOUT_LIST_SRCH
	ADD CONSTRAINT  R_LAYOUT_LIST_SRCH_2__LAYOUT_L FOREIGN KEY (LIST_ID) REFERENCES PLT_LAYOUT_LIST(LIST_ID);



ALTER TABLE PLT_LAYOUT_LIST_STTS
	ADD CONSTRAINT  R_LAYOUT_LIST_STTS_2__LAYOUT_L FOREIGN KEY (LIST_ID) REFERENCES PLT_LAYOUT_LIST(LIST_ID);



ALTER TABLE PLT_LAYOUT_LIST_THUMNAIL
	ADD CONSTRAINT  R_LAYOUT_LIST_THUMNAIL_2__LAYO FOREIGN KEY (LIST_ID) REFERENCES PLT_LAYOUT_LIST(LIST_ID);



ALTER TABLE PLT_LAYOUT_TAB
	ADD CONSTRAINT  R_LAYOUT_TAB_2__LAYOUT_3c FOREIGN KEY (LAYOUT_ID) REFERENCES PLT_LAYOUT(LAYOUT_ID);



COMMENT ON TABLE PLT_LAYOUT IS '레이아웃';
COMMENT ON COLUMN PLT_LAYOUT.LAYOUT_ID IS '레이아웃_ID';
COMMENT ON COLUMN PLT_LAYOUT.LAYOUT_NM IS '레이아웃_명';
COMMENT ON COLUMN PLT_LAYOUT.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LAYOUT.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LAYOUT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LAYOUT.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LAYOUT.LAYOUT_TYPE_CD IS '레이아웃_유형_코드';
COMMENT ON COLUMN PLT_LAYOUT.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_LAYOUT.LAYOUT_CLSF_ID IS '레이아웃_분류_ID';

COMMENT ON TABLE PLT_LAYOUT_LIST IS '레이아웃_목록';
COMMENT ON COLUMN PLT_LAYOUT_LIST.LIST_ID IS '목록_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST.TAB_ID IS 'TAB_ID';

COMMENT ON TABLE PLT_LAYOUT_LIST_DWN_GROUP IS '레이아웃_목록_하위_그룹';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.LIST_DWN_GROUP_ID IS '목록_하위_그룹_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.LIST_ID IS '목록_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.LIST_DWN_GROUP_TTL IS '목록_하위_그룹_제목';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP.WD_SZ IS '가로_크기';

COMMENT ON TABLE PLT_LAYOUT_LIST_DWN_GROUP_DTL IS '레이아웃_목록_하위_그룹_상세';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.LIST_DWN_GROUP_DTL_ID IS '목록_하위_그룹_상세_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.LABEL_NM IS '레이블_명';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.COLOR_CD IS '색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.RSPNS_EPSZ_YN IS '응답_강조_여부';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.RSPNS_COLOR_CD IS '응답_색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.EPSZ_YN IS '강조_여부';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.LIST_DWN_GROUP_ID IS '목록_하위_그룹_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_DWN_GROUP_DTL.RSPNS_ARTCL_ID IS '응답_항목_ID';

COMMENT ON TABLE PLT_LAYOUT_LIST_GROUP IS '레이아웃_목록_그룹';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP.LIST_GROUP_ID IS '목록_그룹_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP.LIST_ID IS '목록_ID';

COMMENT ON TABLE PLT_LAYOUT_LIST_GROUP_DTL IS '레이아웃_목록_그룹_상세';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.LIST_GROUP_DTL_ID IS '목록_그룹_상세_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.LABEL_NM IS '레이블_명';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.COLOR_CD IS '색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.EPSZ_YN IS '강조_여부';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.LIST_GROUP_ID IS '목록_그룹_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.RSPNS_ARTCL_ID IS '응답_항목_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.RSPNS_EPSZ_YN IS '응답_강조_여부';
COMMENT ON COLUMN PLT_LAYOUT_LIST_GROUP_DTL.RSPNS_COLOR_CD IS '응답_색상_코드';

COMMENT ON TABLE PLT_LAYOUT_LIST_SRCH IS '레이아웃_목록_검색';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.LIST_ID IS '목록_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.PARAM_ARTCL_ID IS '파라미터_항목_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_SRCH.GROUP_CD_ID IS '그룹_코드_ID';

COMMENT ON TABLE PLT_LAYOUT_LIST_STTS IS '레이아웃_목록_상태';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.LIST_ID IS '목록_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.RSPNS_ARTCL_ID IS '응답_항목_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.EPSZ_YN IS '강조_여부';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.COLOR_CD IS '색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.SORT_MTHD_CD IS '정렬_방법_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.BG_COLOR_CD IS '배경_색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_LIST_STTS.STTS_NM IS '상태_명';

COMMENT ON TABLE PLT_LAYOUT_LIST_THUMNAIL IS '레이아웃_목록_썸네일';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.LIST_ID IS '목록_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.RSPNS_ARTCL_ID IS '응답_항목_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.WD_SZ IS '가로_크기';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.HT_SZ IS '세로_크기';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.OUTLN_COLOR_CD IS '외곽선_색상_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.OUTLN_TYPE_CD IS '외곽선_유형_코드';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.LN_PX IS '라인_픽셀';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_LIST_THUMNAIL.REG_DT IS '등록_일시';

COMMENT ON TABLE PLT_LAYOUT_TAB IS '레이아웃_TAB';
COMMENT ON COLUMN PLT_LAYOUT_TAB.TAB_ID IS 'TAB_ID';
COMMENT ON COLUMN PLT_LAYOUT_TAB.TAB_NM IS 'TAB_명';
COMMENT ON COLUMN PLT_LAYOUT_TAB.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_TAB.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_TAB.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_TAB.LAYOUT_ID IS '레이아웃_ID';
COMMENT ON COLUMN PLT_LAYOUT_TAB.RSPNS_ARTCL_ID IS '응답_항목_ID';




--검색 기간 코드
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select '*', 'LKAG_SRCH_TERM', custco_id, '검색 기간', '검색 기간', NULL, 'Y', 'Y', 'N', '122', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'LKAG_SRCH_TERM', 'LST_1_DAY', custco_id, '오늘', '오늘', NULL, 'Y', 'Y', 'N', '1', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'LKAG_SRCH_TERM', 'LST_3_DAY', custco_id, '최근 3일', '최근 3일', NULL, 'Y', 'Y', 'N', '2', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'LKAG_SRCH_TERM', 'LST_1_WEEK', custco_id, '최근 1주', '최근 1주', NULL, 'Y', 'Y', 'N', '3', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'LKAG_SRCH_TERM', 'LST_1_MONTH', custco_id, '최근 1달', '최근 1달', NULL, 'Y', 'Y', 'N', '4', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
INSERT INTO PLT_COMM_CD(GROUP_CD_ID,CD_ID,CUSTCO_ID,CD_NM,CD_EXPLN,CD_VL,SYS_CD_YN,USE_YN,DEL_YN,SORT_ORD,RGTR_ID,REG_DT,MDFR_ID,MDFCN_DT)
select 'LKAG_SRCH_TERM', 'LST_3_MONTH', custco_id, '최근 3달', '최근 3달', NULL, 'Y', 'Y', 'N', '5', '2', to_char(now(),'yyyymmddhh24miss'), NULL, NULL from plt_custco ON CONFLICT (group_cd_id, cd_id, custco_id) DO nothing;
			