
CREATE TABLE PLT_OMNI_DMND
(
	OMNI_DMND_ID          BIGSERIAL  NOT NULL ,
	CUSL_ID               BIGINT  NOT NULL ,
	CUST_NM               VARCHAR(300)  NULL ,
	PHN_NO                VARCHAR(60)  NULL ,
	BRDT                  CHAR(8)  NULL ,
	CERT_PVSN_CO_CD       VARCHAR(100)  NULL ,
	AUTHRT_TOKEN          VARCHAR(100)  NULL ,
	CERT_DMND_DT          VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_OMNI_DMND_PK ON PLT_OMNI_DMND
(OMNI_DMND_ID  ASC);



ALTER TABLE PLT_OMNI_DMND
	ADD PRIMARY KEY (OMNI_DMND_ID);



CREATE TABLE PLT_OMNI_RSLT
(
	OMNI_RSLT_ID          BIGSERIAL  NOT NULL ,
	CUSL_ID               BIGINT  NOT NULL ,
	CUST_NM               VARCHAR(300)  NULL ,
	PHN_NO                VARCHAR(60)  NULL ,
	BRDT                  CHAR(8)  NULL ,
	CERT_PVSN_CO_CD       VARCHAR(100)  NULL ,
	AUTHRT_TOKEN          VARCHAR(100)  NULL ,
	RSLT_CD               VARCHAR(60)  NULL ,
	RSLT_ORGNL_TOKEN      TEXT  NULL ,
	RSLT_DECPT_TOKEN      TEXT  NULL ,
	REG_DT                VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_OMNI_RSLT_PK ON PLT_OMNI_RSLT
(OMNI_RSLT_ID  ASC);



ALTER TABLE PLT_OMNI_RSLT
	ADD PRIMARY KEY (OMNI_RSLT_ID);



COMMENT ON TABLE PLT_OMNI_DMND IS 'OMNI_요청';
COMMENT ON COLUMN PLT_OMNI_DMND.OMNI_DMND_ID IS 'OMNI_요청_ID';
COMMENT ON COLUMN PLT_OMNI_DMND.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_OMNI_DMND.CUST_NM IS '고객_명';
COMMENT ON COLUMN PLT_OMNI_DMND.PHN_NO IS '전화_번호';
COMMENT ON COLUMN PLT_OMNI_DMND.BRDT IS '생년월일';
COMMENT ON COLUMN PLT_OMNI_DMND.CERT_PVSN_CO_CD IS '인증_제공_회사_코드';
COMMENT ON COLUMN PLT_OMNI_DMND.AUTHRT_TOKEN IS '권한_토큰';
COMMENT ON COLUMN PLT_OMNI_DMND.CERT_DMND_DT IS '인증_요청_일시';

COMMENT ON TABLE PLT_OMNI_RSLT IS 'OMNI_결과';
COMMENT ON COLUMN PLT_OMNI_RSLT.OMNI_RSLT_ID IS 'OMNI_결과_ID';
COMMENT ON COLUMN PLT_OMNI_RSLT.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_OMNI_RSLT.CUST_NM IS '고객_명';
COMMENT ON COLUMN PLT_OMNI_RSLT.PHN_NO IS '전화_번호';
COMMENT ON COLUMN PLT_OMNI_RSLT.BRDT IS '생년월일';
COMMENT ON COLUMN PLT_OMNI_RSLT.CERT_PVSN_CO_CD IS '인증_제공_회사_코드';
COMMENT ON COLUMN PLT_OMNI_RSLT.AUTHRT_TOKEN IS '권한_토큰';
COMMENT ON COLUMN PLT_OMNI_RSLT.RSLT_ORGNL_TOKEN IS '결과_원본_토큰';
COMMENT ON COLUMN PLT_OMNI_RSLT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_OMNI_RSLT.RSLT_DECPT_TOKEN IS '결과_복호화_토큰';
COMMENT ON COLUMN PLT_OMNI_RSLT.RSLT_CD IS '결과_코드';




