ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_1 VARCHAR(100) NULL;
ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_2 VARCHAR(100) NULL;
ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_3 VARCHAR(100) NULL;
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_1 IS '기타_1';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_2 IS '기타_2';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_3 IS '기타_3';