ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_1 VARCHAR(100) NULL;
ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_2 VARCHAR(100) NULL;
ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS ETC_3 VARCHAR(100) NULL;
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_1 IS '기타_1';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_2 IS '기타_2';
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.ETC_3 IS '기타_3';

ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG ADD IF NOT EXISTS ORDR_INQ_API_ID BIGINT NULL;
ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG ADD IF NOT EXISTS GDS_INQ_API_ID BIGINT NULL;
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.ORDR_INQ_API_ID IS '주문_조회_API_ID';
COMMENT ON COLUMN PLT_CUSTCO_CHN_BBS_STNG.GDS_INQ_API_ID IS '상품_조회_API_ID';

ALTER TABLE PLT_CUSTCO_CHN_BBS_STNG ALTER COLUMN REG_API_ID DROP NOT NULL;

ALTER TABLE PLT_CLCT_JOB_MNG ADD IF NOT EXISTS LAST_SRCH_DT VARCHAR(14) NULL;
COMMENT ON COLUMN PLT_CLCT_JOB_MNG.LAST_SRCH_DT IS '최종_검색_일시';


DROP TABLE PLT_CHT_CUTT_BBS;


ALTER TABLE PLT_ECMRC_INQRY_BBS ADD IF NOT EXISTS CHT_CUTT_ID BIGINT NULL;
COMMENT ON COLUMN PLT_ECMRC_INQRY_BBS.CHT_CUTT_ID IS '채팅_상담_ID';

CREATE INDEX PLT_ECMRC_INQRY_BBS_F2 ON PLT_ECMRC_INQRY_BBS
(CHT_CUTT_ID  ASC);

ALTER TABLE PLT_ECMRC_INQRY_BBS
	ADD CONSTRAINT  R_ECMRC_INQRY_BBS_2__CHT_CUTT_ FOREIGN KEY (CHT_CUTT_ID) REFERENCES PLT_CHT_CUTT(CHT_CUTT_ID);
	

ALTER TABLE PLT_ECMRC_INQRY_BBS RENAME TO PLT_CHT_CUTT_BBS;

ALTER TABLE PLT_ECMRC_INQRY_BBS_ANSWR RENAME TO PLT_CHT_CUTT_BBS_ANSWR;


ALTER TABLE PLT_CHT_CUTT_BBS RENAME COLUMN ECMRC_INQRY_BBS_ID TO CHT_CUTT_BBS_ID;
COMMENT ON COLUMN PLT_CHT_CUTT_BBS.CHT_CUTT_BBS_ID IS '채팅_상담_게시판_ID';

ALTER TABLE PLT_CHT_CUTT_BBS_ANSWR RENAME COLUMN ECMRC_INQRY_BBS_ID TO CHT_CUTT_BBS_ID;
ALTER TABLE PLT_CHT_CUTT_BBS_ANSWR RENAME COLUMN ECMRC_INQRY_BBS_ANSWR_ID TO CHT_CUTT_BBS_ANSWR_ID;
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_ANSWR.CHT_CUTT_BBS_ID IS '채팅_상담_게시판_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_ANSWR.CHT_CUTT_BBS_ANSWR_ID IS '채팅_상담_게시판_답변_ID';
