ALTER TABLE PLT_OMNI_DMND ADD IF NOT EXISTS CUST_ID BIGINT NULL;
ALTER TABLE PLT_OMNI_RSLT ADD IF NOT EXISTS CUST_ID BIGINT NULL;
COMMENT ON COLUMN PLT_OMNI_DMND.CUST_ID IS '고객_ID';
COMMENT ON COLUMN PLT_OMNI_RSLT.CUST_ID IS '고객_ID';


CREATE INDEX PLT_OMNI_DMND_F1 ON PLT_OMNI_DMND
(CUST_ID  ASC);


ALTER TABLE PLT_OMNI_DMND
	ADD CONSTRAINT  R_OMNI_DMND_2__CUST_70 FOREIGN KEY (CUST_ID) REFERENCES PLT_CUST(CUST_ID);


CREATE INDEX PLT_OMNI_RSLT_F1 ON PLT_OMNI_RSLT
(CUST_ID  ASC);



ALTER TABLE PLT_OMNI_RSLT
	ADD CONSTRAINT  R_OMNI_RSLT_2__CUST_fc FOREIGN KEY (CUST_ID) REFERENCES PLT_CUST(CUST_ID);