
CREATE TABLE PLT_CHN_BBS_PARAM_STNG
(
	SNDR_KEY              BIGINT  NOT NULL ,
	API_ID                BIGINT  NOT NULL ,
	PARAM_ARTCL_ID        BIGINT  NOT NULL ,
	ORGNL_PARAM_NM        VARCHAR(100)  NULL ,
	CHG_PARAM_NM          VARCHAR(100)  NULL ,
	ESNTL_YN              CHAR(1)  NULL ,
	ANSWR_PARAM_YN        CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHN_BBS_PARAM_STNG_PK ON PLT_CHN_BBS_PARAM_STNG
(SNDR_KEY  ASC,API_ID  ASC,PARAM_ARTCL_ID  ASC);



ALTER TABLE PLT_CHN_BBS_PARAM_STNG
	ADD PRIMARY KEY (SNDR_KEY,API_ID,PARAM_ARTCL_ID);



CREATE INDEX PLT_CHN_BBS_PARAM_STNG_F1 ON PLT_CHN_BBS_PARAM_STNG
(SNDR_KEY  ASC);



ALTER TABLE PLT_CHN_BBS_PARAM_STNG
	ADD CONSTRAINT  R_CHN_BBS_PARAM_STNG_2__CUSTCO FOREIGN KEY (SNDR_KEY) REFERENCES PLT_CUSTCO_CHN_BBS_STNG(SNDR_KEY);



COMMENT ON TABLE PLT_CHN_BBS_PARAM_STNG IS '채널_게시판_파라미터_설정';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.API_ID IS 'API_ID';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.PARAM_ARTCL_ID IS '파라미터_항목_ID';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.ORGNL_PARAM_NM IS '원본_파라미터_명';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.CHG_PARAM_NM IS '변경_파라미터_명';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.ESNTL_YN IS '필수_여부';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CHN_BBS_PARAM_STNG.ANSWR_PARAM_YN IS '답변_파라미터_여부';




