ALTER TABLE PLT_MENU ADD LAYOUT_ID BIGINT NULL;
ALTER TABLE PLT_BTN ADD LAYOUT_ID BIGINT NULL;
COMMENT ON COLUMN PLT_MENU.LAYOUT_ID IS '레이아웃_ID';
COMMENT ON COLUMN PLT_BTN.LAYOUT_ID IS '레이아웃_ID';

CREATE INDEX PLT_MENU_F3 ON PLT_MENU
(LAYOUT_ID  ASC);

ALTER TABLE PLT_MENU
	ADD CONSTRAINT  R_MENU_2__LAYOUT_88 FOREIGN KEY (LAYOUT_ID) REFERENCES PLT_LAYOUT(LAYOUT_ID);
	
CREATE INDEX PLT_BTN_F2 ON PLT_BTN
(LAYOUT_ID  ASC);


ALTER TABLE PLT_BTN
	ADD CONSTRAINT  R_BTN_2__LAYOUT_fb FOREIGN KEY (LAYOUT_ID) REFERENCES PLT_LAYOUT(LAYOUT_ID);