
CREATE TABLE PLT_CHT_CUTT_BBS_HSTRY
(
	CUTT_BBS_HSTRY_ID     BIGSERIAL  NOT NULL ,
	CHT_CUTT_BBS_ID       BIGINT  NULL ,
	INQRY_CN              TEXT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_CUTT_BBS_HSTRY_PK ON PLT_CHT_CUTT_BBS_HSTRY
(CUTT_BBS_HSTRY_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_BBS_HSTRY
	ADD PRIMARY KEY (CUTT_BBS_HSTRY_ID);



CREATE INDEX PLT_CHT_CUTT_BBS_HSTRY_F1 ON PLT_CHT_CUTT_BBS_HSTRY
(CHT_CUTT_BBS_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_BBS_HSTRY
	ADD CONSTRAINT  R_CHT_CUTT_BBS_HSTRY_2__CHT_CU FOREIGN KEY (CHT_CUTT_BBS_ID) REFERENCES PLT_CHT_CUTT_BBS(CHT_CUTT_BBS_ID);



COMMENT ON TABLE PLT_CHT_CUTT_BBS_HSTRY IS '채팅_상담_게시판_이력';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_HSTRY.CUTT_BBS_HSTRY_ID IS '상담_게시판_이력_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_HSTRY.INQRY_CN IS '문의_내용';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_HSTRY.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CHT_CUTT_BBS_HSTRY.CHT_CUTT_BBS_ID IS '채팅_상담_게시판_ID';




