ALTER TABLE PLT_USER ADD TOKEN VARCHAR(200) NULL;
ALTER TABLE PLT_USER ADD TOKEN_REG_DT VARCHAR(14) NULL;
ALTER TABLE PLT_USER ADD RSVT_ALTMNT_USE_YN CHAR(1) NULL;
COMMENT ON COLUMN PLT_USER.TOKEN IS '토큰';
COMMENT ON COLUMN PLT_USER.TOKEN_REG_DT IS '토큰_등록_일시';
COMMENT ON COLUMN PLT_USER.RSVT_ALTMNT_USE_YN IS '예약_배정_사용_여부';