
CREATE TABLE PLT_CHT_CUTT_RSVT
(
	CHT_CUTT_ID           BIGINT  NOT NULL ,
	RSVT_ID               BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_CHT_CUTT_RSVT_PK ON PLT_CHT_CUTT_RSVT
(CHT_CUTT_ID  ASC,RSVT_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_RSVT
	ADD PRIMARY KEY (CHT_CUTT_ID,RSVT_ID);



CREATE INDEX PLT_CHT_CUTT_RSVT_F1 ON PLT_CHT_CUTT_RSVT
(CHT_CUTT_ID  ASC);



CREATE INDEX PLT_CHT_CUTT_RSVT_F2 ON PLT_CHT_CUTT_RSVT
(RSVT_ID  ASC);



CREATE TABLE PLT_RSVT
(
	RSVT_ID               BIGINT  NOT NULL ,
	CUST_ID               BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	RSVT_DT               VARCHAR(14)  NULL ,
	DRWI_SE_NM            VARCHAR(100)  NULL ,
	STLM_YN               CHAR(1)  NULL ,
	ALTMNT_YN             CHAR(1)  NULL ,
	ALTMNT_DT             VARCHAR(14)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	MDFR_ID               BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_RSVT_PK ON PLT_RSVT
(RSVT_ID  ASC);



ALTER TABLE PLT_RSVT
	ADD PRIMARY KEY (RSVT_ID);



CREATE TABLE PLT_RSVT_ALTMNT
(
	CUSL_ID               BIGINT  NOT NULL ,
	RSVT_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_RSVT_ALTMNT_PK ON PLT_RSVT_ALTMNT
(CUSL_ID  ASC,RSVT_ID  ASC);



ALTER TABLE PLT_RSVT_ALTMNT
	ADD PRIMARY KEY (CUSL_ID,RSVT_ID);



CREATE INDEX PLT_RSVT_ALTMNT_F1 ON PLT_RSVT_ALTMNT
(CUSL_ID  ASC);



CREATE INDEX PLT_RSVT_ALTMNT_F2 ON PLT_RSVT_ALTMNT
(RSVT_ID  ASC);



CREATE TABLE PLT_RSVT_CUTT
(
	RSVT_ID               BIGINT  NOT NULL ,
	PHN_CUTT_ID           BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_RSVT_CUTT_PK ON PLT_RSVT_CUTT
(RSVT_ID  ASC,PHN_CUTT_ID  ASC);



ALTER TABLE PLT_RSVT_CUTT
	ADD PRIMARY KEY (RSVT_ID,PHN_CUTT_ID);



CREATE INDEX PLT_RSVT_CUTT_F1 ON PLT_RSVT_CUTT
(RSVT_ID  ASC);



CREATE INDEX PLT_RSVT_CUTT_F2 ON PLT_RSVT_CUTT
(PHN_CUTT_ID  ASC);



CREATE TABLE PLT_RSVT_CUTT_GUIDE
(
	RSVT_CUTT_GUIDE_ID    BIGINT  NOT NULL ,
	RSVT_ID               BIGINT  NULL ,
	CN                    TEXT  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	MDFR_ID               BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_RSVT_CUTT_GUIDE_PK ON PLT_RSVT_CUTT_GUIDE
(RSVT_CUTT_GUIDE_ID  ASC);



ALTER TABLE PLT_RSVT_CUTT_GUIDE
	ADD PRIMARY KEY (RSVT_CUTT_GUIDE_ID);



CREATE INDEX PLT_RSVT_CUTT_GUIDE_F1 ON PLT_RSVT_CUTT_GUIDE
(RSVT_ID  ASC);



ALTER TABLE PLT_CHT_CUTT_RSVT
	ADD CONSTRAINT  R_CHT_CUTT_RSVT_2__CHT_CUTT_b5 FOREIGN KEY (CHT_CUTT_ID) REFERENCES PLT_CHT_CUTT(CHT_CUTT_ID);



ALTER TABLE PLT_CHT_CUTT_RSVT
	ADD CONSTRAINT  R_CHT_CUTT_RSVT_2__RSVT_58 FOREIGN KEY (RSVT_ID) REFERENCES PLT_RSVT(RSVT_ID);



ALTER TABLE PLT_RSVT_ALTMNT
	ADD CONSTRAINT  R_RSVT_ALTMNT_2__USER_31 FOREIGN KEY (CUSL_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_RSVT_ALTMNT
	ADD CONSTRAINT  R_RSVT_ALTMNT_2__RSVT_26 FOREIGN KEY (RSVT_ID) REFERENCES PLT_RSVT(RSVT_ID);



ALTER TABLE PLT_RSVT_CUTT
	ADD CONSTRAINT  R_RSVT_CUTT_2__RSVT_d1 FOREIGN KEY (RSVT_ID) REFERENCES PLT_RSVT(RSVT_ID);



ALTER TABLE PLT_RSVT_CUTT
	ADD CONSTRAINT  R_RSVT_CUTT_2__PHN_CUTT_12 FOREIGN KEY (PHN_CUTT_ID) REFERENCES PLT_PHN_CUTT(PHN_CUTT_ID);



ALTER TABLE PLT_RSVT_CUTT_GUIDE
	ADD CONSTRAINT  R_RSVT_CUTT_GUIDE_2__RSVT_3e FOREIGN KEY (RSVT_ID) REFERENCES PLT_RSVT(RSVT_ID);



COMMENT ON TABLE PLT_CHT_CUTT_RSVT IS '채팅_상담_예약';
COMMENT ON COLUMN PLT_CHT_CUTT_RSVT.CHT_CUTT_ID IS '채팅_상담_ID';
COMMENT ON COLUMN PLT_CHT_CUTT_RSVT.RSVT_ID IS '예약_ID';

COMMENT ON TABLE PLT_RSVT IS '예약';
COMMENT ON COLUMN PLT_RSVT.RSVT_ID IS '예약_ID';
COMMENT ON COLUMN PLT_RSVT.CUST_ID IS '고객_ID';
COMMENT ON COLUMN PLT_RSVT.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_RSVT.RSVT_DT IS '예약_일시';
COMMENT ON COLUMN PLT_RSVT.DRWI_SE_NM IS '인입_구분_명';
COMMENT ON COLUMN PLT_RSVT.ALTMNT_YN IS '배정_여부';
COMMENT ON COLUMN PLT_RSVT.ALTMNT_DT IS '배정_일시';
COMMENT ON COLUMN PLT_RSVT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_RSVT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_RSVT.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_RSVT.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_RSVT.STLM_YN IS '결제_여부';

COMMENT ON TABLE PLT_RSVT_ALTMNT IS '예약_배정';
COMMENT ON COLUMN PLT_RSVT_ALTMNT.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT.RSVT_ID IS '예약_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_RSVT_ALTMNT.RGTR_ID IS '등록자_ID';

COMMENT ON TABLE PLT_RSVT_CUTT IS '예약_상담';
COMMENT ON COLUMN PLT_RSVT_CUTT.RSVT_ID IS '예약_ID';
COMMENT ON COLUMN PLT_RSVT_CUTT.PHN_CUTT_ID IS '전화_상담_ID';

COMMENT ON TABLE PLT_RSVT_CUTT_GUIDE IS '예약_상담_안내';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.RSVT_CUTT_GUIDE_ID IS '예약_상담_안내_ID';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.CN IS '내용';
COMMENT ON COLUMN PLT_RSVT_CUTT_GUIDE.RSVT_ID IS '예약_ID';




