ALTER TABLE PLT_PHN_CUTT ADD IF NOT EXISTS VIDEO_FILE_PATH VARCHAR(1000) NULL;
COMMENT ON COLUMN PLT_PHN_CUTT.VIDEO_FILE_PATH IS '비디오_파일_경로';

ALTER TABLE PLT_CHT_CUTT ADD IF NOT EXISTS VIDEO_FILE_PATH VARCHAR(1000) NULL;
COMMENT ON COLUMN PLT_CHT_CUTT.VIDEO_FILE_PATH IS '비디오_파일_경로';


ALTER TABLE PLT_OGNZ ADD IF NOT EXISTS CO_SE_CD VARCHAR(60) NULL;
COMMENT ON COLUMN PLT_OGNZ.CO_SE_CD IS '회사_구분_코드';