ALTER TABLE PLT_RSVT ADD IF NOT EXISTS SW_RSVT_ID VARCHAR(60) NULL;
ALTER TABLE PLT_RSVT ADD IF NOT EXISTS SW_ANLS_ID VARCHAR(60) NULL;
ALTER TABLE PLT_RSVT ADD IF NOT EXISTS BRNCH_NM VARCHAR(100) NULL;
COMMENT ON COLUMN PLT_RSVT.SW_RSVT_ID IS 'SW_예약_ID';
COMMENT ON COLUMN PLT_RSVT.SW_ANLS_ID IS 'SW_분석_ID';
COMMENT ON COLUMN PLT_RSVT.BRNCH_NM IS '지점_명';