ALTER TABLE PLT_SRVY_QITEM_GROUP ADD IF NOT EXISTS ORGNL_SRVY_QITEM_GROUP_ID BIGINT NULL;
COMMENT ON COLUMN PLT_SRVY_QITEM_GROUP.ORGNL_SRVY_QITEM_GROUP_ID IS '원본_설문_문항_그룹_ID';

ALTER TABLE PLT_SRVY_QITEM ADD IF NOT EXISTS ORGNL_SRVY_QITEM_ID BIGINT NULL;
COMMENT ON COLUMN PLT_SRVY_QITEM.ORGNL_SRVY_QITEM_ID IS '원본_설문_문항_ID';