INSERT INTO PLT_BTN (BTN_ID, MENU_ID, SCRN_BTN_ID, SCRN_BTN_NM, BTN_TYPE, RGTR_ID, REG_DT)
SELECT getSeqNo('BTN_ID'), PM.MENU_ID, 'btnCuttHistExcelDown', '엑셀 다운로드', 'OUPT', 2, to_char(now(),'yyyymmddhh24miss')
FROM PLT_MENU PM
WHERE PM.PATH_NM = '/CSL_M0301' AND PM.VIEW_TRGT = 'MAIN'
AND NOT EXISTS (SELECT 1 FROM PLT_BTN A WHERE A.MENU_ID = PM.MENU_ID AND A.SCRN_BTN_ID = 'btnCuttHistExcelDown');


INSERT INTO PLT_BTN_AUTHRT (AUTHRT_GROUP_ID, MENU_ID, BTN_ID, RGTR_ID, REG_DT)
SELECT PA.AUTHRT_GROUP_ID, PB.MENU_ID, PB.BTN_ID, 2, to_char(now(),'yyyymmddhh24miss')
FROM PLT_AUTHRT PA
INNER JOIN PLT_AUTHRT_GROUP_PRGRM PAGP ON PAGP.AUTHRT_GROUP_ID = PA.AUTHRT_GROUP_ID
INNER JOIN PLT_BTN PB ON PB.MENU_ID = PAGP.MENU_ID AND SCRN_BTN_ID = 'btnCuttHistExcelDown'
INNER JOIN PLT_MENU PM ON PM.MENU_ID = PB.MENU_ID AND PM.PATH_NM = '/CSL_M0301' AND PM.VIEW_TRGT = 'MAIN'
ON CONFLICT (AUTHRT_GROUP_ID, MENU_ID, BTN_ID) DO NOTHING;


INSERT INTO PLT_BTN (BTN_ID, MENU_ID, SCRN_BTN_ID, SCRN_BTN_NM, BTN_TYPE, RGTR_ID, REG_DT)
SELECT getSeqNo('BTN_ID'), PM.MENU_ID, 'btnCustListExcelDown', '엑셀 다운로드', 'OUPT', 2, to_char(now(),'yyyymmddhh24miss')
FROM PLT_MENU PM
WHERE PM.PATH_NM = '/STG_M0402' AND PM.VIEW_TRGT = 'MAIN'
AND NOT EXISTS (SELECT 1 FROM PLT_BTN A WHERE A.MENU_ID = PM.MENU_ID AND A.SCRN_BTN_ID = 'btnCustListExcelDown');


INSERT INTO PLT_BTN_AUTHRT (AUTHRT_GROUP_ID, MENU_ID, BTN_ID, RGTR_ID, REG_DT)
SELECT PA.AUTHRT_GROUP_ID, PB.MENU_ID, PB.BTN_ID, 2, to_char(now(),'yyyymmddhh24miss')
FROM PLT_AUTHRT PA
INNER JOIN PLT_AUTHRT_GROUP_PRGRM PAGP ON PAGP.AUTHRT_GROUP_ID = PA.AUTHRT_GROUP_ID
INNER JOIN PLT_BTN PB ON PB.MENU_ID = PAGP.MENU_ID AND SCRN_BTN_ID = 'btnCustListExcelDown'
INNER JOIN PLT_MENU PM ON PM.MENU_ID = PB.MENU_ID AND PM.PATH_NM = '/STG_M0402' AND PM.VIEW_TRGT = 'MAIN'
ON CONFLICT (AUTHRT_GROUP_ID, MENU_ID, BTN_ID) DO NOTHING;
