
CREATE TABLE PLT_RSVT_ALTMNT_HSTRY
(
	RSVT_ALTMNT_HSTRY_ID  BIGSERIAL  NOT NULL ,
	RSVT_ID               BIGINT  NULL ,
	BFR_CUSL_ID           BIGINT  NOT NULL ,
	AFTR_CUSL_ID          BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_RSVT_ALTMNT_HSTRY_PK ON PLT_RSVT_ALTMNT_HSTRY
(RSVT_ALTMNT_HSTRY_ID  ASC);



ALTER TABLE PLT_RSVT_ALTMNT_HSTRY
	ADD PRIMARY KEY (RSVT_ALTMNT_HSTRY_ID);



CREATE INDEX PLT_RSVT_ALTMNT_HSTRY_F1 ON PLT_RSVT_ALTMNT_HSTRY
(RSVT_ID  ASC);



ALTER TABLE PLT_RSVT_ALTMNT_HSTRY
	ADD CONSTRAINT  R_RSVT_ALTMNT_HSTRY_2__RSVT_60 FOREIGN KEY (RSVT_ID) REFERENCES PLT_RSVT(RSVT_ID);



COMMENT ON TABLE PLT_RSVT_ALTMNT_HSTRY IS '예약_배정_이력';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.RSVT_ALTMNT_HSTRY_ID IS '예약_배정_이력_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.RSVT_ID IS '예약_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.BFR_CUSL_ID IS '이전_상담사_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_RSVT_ALTMNT_HSTRY.AFTR_CUSL_ID IS '이후_상담사_ID';




