INSERT INTO PLT_COMM_CD (GROUP_CD_ID, CD_ID, CUSTCO_ID, CD_NM, CD_EXPLN, SYS_CD_YN, USE_YN, DEL_YN, SORT_ORD, RGTR_ID, REG_DT, MDFR_ID, MDFCN_DT)
SELECT 'MSG_TMPL_TP', 'TP_VIDEO', CUSTCO_ID, '영상통화 링크 정보 템플릿', '영상통화 링크 정보 템플릿', 'Y', 'Y', 'N', 4, 2, TO_CHAR(NOW(), 'YYYYMMDDHH24MISS'), 2, TO_CHAR(NOW(), 'YYYYMMDDHH24MISS') FROM PLT_CUSTCO
ON CONFLICT (CUSTCO_ID, GROUP_CD_ID, CD_ID) DO NOTHING;