CREATE TABLE PLT_CUTT_TRNSF
(
	CUTT_TRNSF_ID         BIGINT  NOT NULL ,
	ITGRT_HSTRY_ID        BIGINT  NULL ,
	DMND_CUSL_ID          BIGINT  NOT NULL ,
	TRGT_USER_ID          BIGINT  NOT NULL ,
	STTS_CD               VARCHAR(60)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CUTT_TRNSF_PK ON PLT_CUTT_TRNSF
(CUTT_TRNSF_ID  ASC);



ALTER TABLE PLT_CUTT_TRNSF
	ADD PRIMARY KEY (CUTT_TRNSF_ID);



CREATE INDEX PLT_CUTT_TRNSF_F1 ON PLT_CUTT_TRNSF
(ITGRT_HSTRY_ID  ASC);



CREATE TABLE PLT_CUTT_TRNSF_EXPSN_ATTR
(
	CUTT_TRNSF_ID         BIGINT  NOT NULL ,
	ATTR_ID               BIGINT  NOT NULL ,
	ATTR_VL               TEXT  NULL 
);



CREATE UNIQUE INDEX PLT_CUTT_TRNSF_EXPSN_ATTR_PK ON PLT_CUTT_TRNSF_EXPSN_ATTR
(CUTT_TRNSF_ID  ASC,ATTR_ID  ASC);



ALTER TABLE PLT_CUTT_TRNSF_EXPSN_ATTR
	ADD PRIMARY KEY (CUTT_TRNSF_ID,ATTR_ID);



CREATE INDEX PLT_CUTT_TRNSF_EXPSN_ATTR_F1 ON PLT_CUTT_TRNSF_EXPSN_ATTR
(CUTT_TRNSF_ID  ASC);



CREATE INDEX PLT_CUTT_TRNSF_EXPSN_ATTR_F2 ON PLT_CUTT_TRNSF_EXPSN_ATTR
(ATTR_ID  ASC);



CREATE TABLE PLT_CUTT_TRNSF_HSTRY
(
	CUTT_TRNSF_HSTRY_ID   BIGINT  NOT NULL ,
	CUTT_TRNSF_ID         BIGINT  NULL ,
	STTS_CD               VARCHAR(60)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_CUTT_TRNSF_HSTRY_PK ON PLT_CUTT_TRNSF_HSTRY
(CUTT_TRNSF_HSTRY_ID  ASC);



ALTER TABLE PLT_CUTT_TRNSF_HSTRY
	ADD PRIMARY KEY (CUTT_TRNSF_HSTRY_ID);



CREATE INDEX PLT_CUTT_TRNSF_HSTRY_F1 ON PLT_CUTT_TRNSF_HSTRY
(CUTT_TRNSF_ID  ASC);



ALTER TABLE PLT_CUTT_TRNSF
	ADD CONSTRAINT  R_CUTT_TRNSF_2__CUTT_ITGRT_HST FOREIGN KEY (ITGRT_HSTRY_ID) REFERENCES PLT_CUTT_ITGRT_HSTRY(ITGRT_HSTRY_ID);



ALTER TABLE PLT_CUTT_TRNSF_EXPSN_ATTR
	ADD CONSTRAINT  R_CUTT_TRNSF_EXPSN_ATTR_2__CUT FOREIGN KEY (CUTT_TRNSF_ID) REFERENCES PLT_CUTT_TRNSF(CUTT_TRNSF_ID);



ALTER TABLE PLT_CUTT_TRNSF_EXPSN_ATTR
	ADD CONSTRAINT  R_CUTT_TRNSF_EXPSN_ATTR_2__EXP FOREIGN KEY (ATTR_ID) REFERENCES PLT_EXPSN_ATTR(ATTR_ID);



ALTER TABLE PLT_CUTT_TRNSF_HSTRY
	ADD CONSTRAINT  R_CUTT_TRNSF_HSTRY_2__CUTT_TRN FOREIGN KEY (CUTT_TRNSF_ID) REFERENCES PLT_CUTT_TRNSF(CUTT_TRNSF_ID);



COMMENT ON TABLE PLT_CUTT_TRNSF IS '상담_이관';
COMMENT ON COLUMN PLT_CUTT_TRNSF.CUTT_TRNSF_ID IS '상담_이관_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF.ITGRT_HSTRY_ID IS '통합_이력_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF.DMND_CUSL_ID IS '요청_상담사_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF.STTS_CD IS '상태_코드';
COMMENT ON COLUMN PLT_CUTT_TRNSF.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CUTT_TRNSF.TRGT_USER_ID IS '대상_사용자_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_CUTT_TRNSF_EXPSN_ATTR IS '상담_이관_확장_속성';
COMMENT ON COLUMN PLT_CUTT_TRNSF_EXPSN_ATTR.CUTT_TRNSF_ID IS '상담_이관_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_EXPSN_ATTR.ATTR_ID IS '속성_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_EXPSN_ATTR.ATTR_VL IS '속성_값';

COMMENT ON TABLE PLT_CUTT_TRNSF_HSTRY IS '상담_이관_이력';
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.CUTT_TRNSF_HSTRY_ID IS '상담_이관_이력_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.STTS_CD IS '상태_코드';
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.CUTT_TRNSF_ID IS '상담_이관_ID';