ALTER TABLE PLT_CUTT_TRNSF ADD IF NOT EXISTS RSN VARCHAR(2000) NULL;
COMMENT ON COLUMN PLT_CUTT_TRNSF.RSN IS '사유';
ALTER TABLE PLT_CUTT_TRNSF_HSTRY ADD IF NOT EXISTS RSN VARCHAR(2000) NULL;
COMMENT ON COLUMN PLT_CUTT_TRNSF_HSTRY.RSN IS '사유';