ALTER TABLE PLT_PST_CMNT
ADD COLUMN HIGR_CMNT_ID int8;

ALTER TABLE PLT_PST_CMNT
ADD COLUMN USE_YN bpchar(1) NULL;

ALTER TABLE PLT_PST_CMNT
ADD COLUMN MDFR_ID int8 NULL;

ALTER TABLE PLT_PST_CMNT
ADD COLUMN MDFCN_ID varchar(14) NULL;

COMMENT ON COLUMN PLT_PST_CMNT.HIGR_CMNT_ID IS '상위_댓글_ID';
COMMENT ON COLUMN PLT_PST_CMNT.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_PST_CMNT.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_PST_CMNT.MDFCN_ID IS '수정_일시';