CREATE TABLE IF NOT EXISTS PLT_CUTT_TRNSF_ALTMNT
(
	CUTT_TRNSF_ID		BIGINT NOT NULL ,
	CUSL_ID				BIGINT NOT NULL ,
	RGTR_ID				BIGINT NOT NULL ,
	REG_DT              VARCHAR(14) NOT NULL
);

	
CREATE TABLE IF NOT EXISTS PLT_CUTT_TRNSF_ALTMNT_HSTRY
(
	CUTT_TRNSF_ALTMNT_HSTRY_ID		BIGINT NOT NULL ,
	CUTT_TRNSF_ID					BIGINT NOT NULL ,
	CUSL_ID							BIGINT NOT NULL ,
	TYPE              				VARCHAR(14) NOT NULL ,
	RGTR_ID							BIGINT NOT NULL ,
	REG_DT              			VARCHAR(14) NOT NULL
);


COMMENT ON TABLE PLT_CUTT_TRNSF_ALTMNT IS '이관_전화_상담_배정';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT.CUTT_TRNSF_ID IS '상담_이관_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT.REG_DT IS '등록_일시';

COMMENT ON TABLE PLT_CUTT_TRNSF_ALTMNT_HSTRY IS '이관_전화_상담_배정_이력';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT_HSTRY.CUTT_TRNSF_ALTMNT_HSTRY_ID IS '상담_이관_배정_이력_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT_HSTRY.CUTT_TRNSF_ID IS '상담_이관_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT_HSTRY.TYPE IS '이벤트_유형';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT_HSTRY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUTT_TRNSF_ALTMNT_HSTRY.REG_DT IS '등록_일시';

ALTER TABLE PLT_CUTT_TRNSF ADD TARGET_OPT_CD varchar(60) NULL;
COMMENT ON COLUMN PLT_CUTT_TRNSF.TARGET_OPT_CD IS '담당자_옵션_코드';

