###################################################
# localkm profile
###################################################
spring.profiles:
  -local-km

##spring.profiles.include: "km"
spring.profiles.include: 
  -km

###################################################
#
# 지식(km) 속성
# -------------------------------------------------
# include 'km' profile
###################################################
---
spring.config.activate:
  on-profile: "km"
# ----------------------------------------
# KmProperties
# ----------------------------------------
km:
  enabled: true
  # ----------------------------------------
  # 검색엔진
  # ----------------------------------------
  search-engine:
    search-engine-ip: "210.112.73.26"
    search-engine-port: 5555

