
CREATE TABLE PLT_AUTHRT
(
	AUTHRT_GROUP_ID       BIGINT  NOT NULL ,
	AUTHRT_GROUP_NM       VARCHAR(300)  NULL ,
	GROUP_EXPLN           VARCHAR(1000)  NULL ,
	MNGR_PM_CD            VARCHAR(60)  NULL ,
	ETC_INFO_01           VARCHAR(500)  NULL ,
	ETC_INFO_02           VARCHAR(500)  NULL ,
	ETC_INFO_03           VARCHAR(500)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	SORT_ORD              INT  NULL ,
	USER_SE_CD            VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_AUTHRT_PK ON PLT_AUTHRT
(AUTHRT_GROUP_ID  ASC);



ALTER TABLE PLT_AUTHRT
	ADD PRIMARY KEY (AUTHRT_GROUP_ID);



CREATE TABLE PLT_AUTHRT_GROUP_PRGRM
(
	AUTHRT_GROUP_ID       BIGINT  NOT NULL ,
	MENU_ID               BIGINT  NOT NULL ,
	INQ_AUTHRT            INT  NULL ,
	PRCS_AUTHRT           INT  NULL ,
	DEL_AUTHRT            INT  NULL ,
	OTPT_AUTHRT           INT  NULL ,
	EXCL_AUTHRT           INT  NULL ,
	ADD_AUTHRT            INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_AUTHRT_GROUP_PRGRM_PK ON PLT_AUTHRT_GROUP_PRGRM
(AUTHRT_GROUP_ID  ASC,MENU_ID  ASC);



ALTER TABLE PLT_AUTHRT_GROUP_PRGRM
	ADD PRIMARY KEY (AUTHRT_GROUP_ID,MENU_ID);



CREATE INDEX PLT_AUTHRT_GROUP_PRGRM_F1 ON PLT_AUTHRT_GROUP_PRGRM
(AUTHRT_GROUP_ID  ASC);



CREATE INDEX PLT_AUTHRT_GROUP_PRGRM_F2 ON PLT_AUTHRT_GROUP_PRGRM
(MENU_ID  ASC);



CREATE TABLE PLT_BTN
(
	BTN_ID                BIGINT  NOT NULL ,
	MENU_ID               BIGINT  NULL ,
	SCRN_BTN_ID           VARCHAR(40)  NULL ,
	SCRN_BTN_NM           VARCHAR(100)  NULL ,
	BTN_TYPE              VARCHAR(60)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_BTN_PK ON PLT_BTN
(BTN_ID  ASC);



ALTER TABLE PLT_BTN
	ADD PRIMARY KEY (BTN_ID);



CREATE INDEX PLT_BTN_F1 ON PLT_BTN
(MENU_ID  ASC);



CREATE TABLE PLT_BTN_AUTHRT
(
	AUTHRT_GROUP_ID       BIGINT  NOT NULL ,
	MENU_ID               BIGINT  NOT NULL ,
	BTN_ID                BIGINT  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_BTN_AUTHRT_PK ON PLT_BTN_AUTHRT
(AUTHRT_GROUP_ID  ASC,MENU_ID  ASC,BTN_ID  ASC);



ALTER TABLE PLT_BTN_AUTHRT
	ADD PRIMARY KEY (AUTHRT_GROUP_ID,MENU_ID,BTN_ID);



CREATE INDEX PLT_BTN_AUTHRT_F1 ON PLT_BTN_AUTHRT
(AUTHRT_GROUP_ID  ASC,MENU_ID  ASC);



CREATE INDEX PLT_BTN_AUTHRT_F2 ON PLT_BTN_AUTHRT
(BTN_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	CUSTCO_NM             VARCHAR(200)  NULL ,
	SCHEMA_ID             VARCHAR(200)  NULL ,
	ASP_CUST_KEY          VARCHAR(100)  NULL ,
	CUSTCO_SE_CD          VARCHAR(60)  NULL ,
	SIC                   VARCHAR(60)  NULL ,
	CRNO                  CHAR(13)  NULL ,
	BRNO                  CHAR(10)  NULL ,
	RPRS_PHN_NO           VARCHAR(60)  NULL ,
	ZIP                   VARCHAR(12)  NULL ,
	ADDR                  VARCHAR(200)  NULL ,
	DTL_ADDR              VARCHAR(200)  NULL ,
	APLY_DT               VARCHAR(14)  NULL ,
	APLY_SE_CD            VARCHAR(60)  NULL ,
	APLY_USER_NM          VARCHAR(20)  NULL ,
	GEND                  VARCHAR(60)  NULL ,
	REL_SE_CD             VARCHAR(60)  NULL ,
	APLY_USER_EXT_NO      VARCHAR(60)  NULL ,
	APLY_USER_PHN_NO      VARCHAR(60)  NULL ,
	EML                   VARCHAR(60)  NULL ,
	SRVC_BGNG_DT          VARCHAR(14)  NULL ,
	SRVC_END_DT           VARCHAR(14)  NULL ,
	SRVC_STTS_CD          VARCHAR(60)  NULL ,
	USER_ACNT_CNT         INT  NULL ,
	USER_LGN_SMS_CERT_YN  CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	IPCC_SRVR_ID          BIGINT  NULL ,
	SRVC_CRT_DT           VARCHAR(14)  NULL ,
	SRVC_GDS_ID           BIGINT  NULL ,
	BFR_SYS_YN            CHAR(1)  NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	ICON_FILE_GROUP_KEY   VARCHAR(90)  NULL ,
	IMG_FILE_GROUP_KEY    VARCHAR(90)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_PK ON PLT_CERT_CUSTCO
(CERT_CUSTCO_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO
	ADD PRIMARY KEY (CERT_CUSTCO_ID);



CREATE INDEX PLT_CERT_CUSTCO_F1 ON PLT_CERT_CUSTCO
(IPCC_SRVR_ID  ASC);



CREATE INDEX PLT_CERT_CUSTCO_F2 ON PLT_CERT_CUSTCO
(SRVC_GDS_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_CHN
(
	SNDR_KEY              BIGINT  NOT NULL ,
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	DSPTCH_PRF_KEY        VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_CHN_PK ON PLT_CERT_CUSTCO_CHN
(SNDR_KEY  ASC,CERT_CUSTCO_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_CHN
	ADD PRIMARY KEY (SNDR_KEY,CERT_CUSTCO_ID);



CREATE INDEX PLT_CERT_CUSTCO_CHN_F1 ON PLT_CERT_CUSTCO_CHN
(CERT_CUSTCO_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_DSPTCH_NO
(
	CERT_CUSTCO_DSPTCH_NO_ID  BIGINT  NOT NULL ,
	CERT_CUSTCO_ID        BIGINT  NULL ,
	RPRS_NO               VARCHAR(60)  NULL ,
	DSPTCH_NO             VARCHAR(60)  NULL ,
	DSPTCH_NM             VARCHAR(200)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_DSPTCH_NO_PK ON PLT_CERT_CUSTCO_DSPTCH_NO
(CERT_CUSTCO_DSPTCH_NO_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_DSPTCH_NO
	ADD PRIMARY KEY (CERT_CUSTCO_DSPTCH_NO_ID);



CREATE INDEX PLT_CERT_CUSTCO_DSPTCH_NO_F1 ON PLT_CERT_CUSTCO_DSPTCH_NO
(CERT_CUSTCO_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_LANG
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	LANG_CD               VARCHAR(60)  NOT NULL ,
	YMD_EXPSR_MTHD_CD     VARCHAR(60)  NULL ,
	YMD_SE_CD             VARCHAR(60)  NULL ,
	BSC_LANG_YN           CHAR(1)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_LANG_PK ON PLT_CERT_CUSTCO_LANG
(CERT_CUSTCO_ID  ASC,LANG_CD  ASC);



ALTER TABLE PLT_CERT_CUSTCO_LANG
	ADD PRIMARY KEY (CERT_CUSTCO_ID,LANG_CD);



CREATE INDEX PLT_CERT_CUSTCO_LANG_F1 ON PLT_CERT_CUSTCO_LANG
(CERT_CUSTCO_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_LKAG
(
	CERT_CUSTCO_LKAG_ID   BIGINT  NOT NULL ,
	CERT_CUSTCO_ID        BIGINT  NULL ,
	LKAG_ID               BIGINT  NULL ,
	ACS_ACNT_KEY          VARCHAR(200)  NULL ,
	ACS_SECTY_KEY         VARCHAR(200)  NULL ,
	ACS_ACNT_ID           VARCHAR(200)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_LKAG_PK ON PLT_CERT_CUSTCO_LKAG
(CERT_CUSTCO_LKAG_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_LKAG
	ADD PRIMARY KEY (CERT_CUSTCO_LKAG_ID);



CREATE INDEX PLT_CERT_CUSTCO_LKAG_F1 ON PLT_CERT_CUSTCO_LKAG
(CERT_CUSTCO_ID  ASC);



CREATE INDEX PLT_CERT_CUSTCO_LKAG_F2 ON PLT_CERT_CUSTCO_LKAG
(LKAG_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_SRVC
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	SRVC_GDS_DTL_ID       BIGINT  NOT NULL ,
	USE_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_SRVC_PK ON PLT_CERT_CUSTCO_SRVC
(CERT_CUSTCO_ID  ASC,SRVC_GDS_DTL_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_SRVC
	ADD PRIMARY KEY (CERT_CUSTCO_ID,SRVC_GDS_DTL_ID);



CREATE INDEX PLT_CERT_CUSTCO_SRVC_F1 ON PLT_CERT_CUSTCO_SRVC
(CERT_CUSTCO_ID  ASC);



CREATE INDEX PLT_CERT_CUSTCO_SRVC_F2 ON PLT_CERT_CUSTCO_SRVC
(SRVC_GDS_DTL_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_SRVC_INST
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	INST_CD               VARCHAR(60)  NOT NULL ,
	SRVC_GDS_DTL_ID       BIGINT  NOT NULL ,
	INST_NM               VARCHAR(100)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_SRVC_INST_PK ON PLT_CERT_CUSTCO_SRVC_INST
(CERT_CUSTCO_ID  ASC,INST_CD  ASC,SRVC_GDS_DTL_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_SRVC_INST
	ADD PRIMARY KEY (CERT_CUSTCO_ID,INST_CD,SRVC_GDS_DTL_ID);



CREATE INDEX PLT_CERT_CUSTCO_SRVC_INST_F1 ON PLT_CERT_CUSTCO_SRVC_INST
(CERT_CUSTCO_ID  ASC,SRVC_GDS_DTL_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_SRVC_KEY
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	SRVC_GDS_DTL_ID       BIGINT  NOT NULL ,
	CUSTCO_CD             VARCHAR(40)  NULL ,
	SRVC_KEY              VARCHAR(200)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_SRVC_KEY_PK ON PLT_CERT_CUSTCO_SRVC_KEY
(CERT_CUSTCO_ID  ASC,SRVC_GDS_DTL_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_SRVC_KEY
	ADD PRIMARY KEY (CERT_CUSTCO_ID,SRVC_GDS_DTL_ID);



CREATE INDEX PLT_CERT_CUSTCO_SRVC_KEY_F2 ON PLT_CERT_CUSTCO_SRVC_KEY
(CERT_CUSTCO_ID  ASC,SRVC_GDS_DTL_ID  ASC);



CREATE TABLE PLT_CERT_CUSTCO_USER
(
	CERT_CUSTCO_ID        BIGINT  NOT NULL ,
	CERT_USER_ID          BIGINT  NOT NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_CUSTCO_USER_PK ON PLT_CERT_CUSTCO_USER
(CERT_CUSTCO_ID  ASC,CERT_USER_ID  ASC);



ALTER TABLE PLT_CERT_CUSTCO_USER
	ADD PRIMARY KEY (CERT_CUSTCO_ID,CERT_USER_ID);



CREATE INDEX PLT_CERT_CUSTCO_USER_F1 ON PLT_CERT_CUSTCO_USER
(CERT_CUSTCO_ID  ASC);



CREATE INDEX PLT_CERT_CUSTCO_USER_F2 ON PLT_CERT_CUSTCO_USER
(CERT_USER_ID  ASC);



CREATE TABLE PLT_CERT_IPCC_SRVR
(
	IPCC_SRVR_ID          BIGINT  NOT NULL ,
	SRVR_NM               VARCHAR(200)  NULL ,
	API_URI               VARCHAR(600)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	SRVR_STTS_CD          VARCHAR(60)  NULL ,
	IP                    VARCHAR(100)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_IPCC_SRVR_PK ON PLT_CERT_IPCC_SRVR
(IPCC_SRVR_ID  ASC);



ALTER TABLE PLT_CERT_IPCC_SRVR
	ADD PRIMARY KEY (IPCC_SRVR_ID);



CREATE TABLE PLT_CERT_SRVC_GDS
(
	SRVC_GDS_ID           BIGINT  NOT NULL ,
	SRVC_GDS_NM           VARCHAR(200)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_SRVC_GDS_PK ON PLT_CERT_SRVC_GDS
(SRVC_GDS_ID  ASC);



ALTER TABLE PLT_CERT_SRVC_GDS
	ADD PRIMARY KEY (SRVC_GDS_ID);



CREATE TABLE PLT_CERT_SRVC_GDS_DTL
(
	SRVC_GDS_DTL_ID       BIGINT  NOT NULL ,
	SRVC_GDS_ID           BIGINT  NULL ,
	SRVC_GDS_DTL_CD       VARCHAR(60)  NOT NULL ,
	NTSL_YN               CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_SRVC_GDS_DTL_PK ON PLT_CERT_SRVC_GDS_DTL
(SRVC_GDS_DTL_ID  ASC);



ALTER TABLE PLT_CERT_SRVC_GDS_DTL
	ADD PRIMARY KEY (SRVC_GDS_DTL_ID);



CREATE INDEX PLT_CERT_SRVC_GDS_DTL_F1 ON PLT_CERT_SRVC_GDS_DTL
(SRVC_GDS_ID  ASC);



CREATE TABLE PLT_CERT_USER
(
	CERT_USER_ID          BIGINT  NOT NULL ,
	LGN_ID                VARCHAR(100)  NULL 
);



CREATE UNIQUE INDEX PLT_CERT_USER_PK ON PLT_CERT_USER
(CERT_USER_ID  ASC);



ALTER TABLE PLT_CERT_USER
	ADD PRIMARY KEY (CERT_USER_ID);



CREATE TABLE PLT_CHT_CUSTCO_SYS_MSG
(
	CUSTCO_ID             BIGINT  NOT NULL ,
	SYS_MSG_ID            BIGINT  NOT NULL ,
	MSG_HR                INT  NOT NULL ,
	MSG_TYPE_CD           VARCHAR(60)  NULL ,
	MSG_CN                VARCHAR(4000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_CUSTCO_SYS_MSG_PK ON PLT_CHT_CUSTCO_SYS_MSG
(CUSTCO_ID  ASC,SYS_MSG_ID  ASC,MSG_HR  ASC);



ALTER TABLE PLT_CHT_CUSTCO_SYS_MSG
	ADD PRIMARY KEY (CUSTCO_ID,SYS_MSG_ID,MSG_HR);



CREATE TABLE PLT_CHT_RDY_ONOFF_HSTRY
(
	CUSL_ID               BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	STTS_CD               VARCHAR(60)  NULL ,
	CUTT_BGNG_DT          VARCHAR(14)  NULL ,
	CUTT_END_DT           VARCHAR(14)  NULL ,
	PRCS_HR               VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_RDY_ONOFF_HSTRY_PK ON PLT_CHT_RDY_ONOFF_HSTRY
(CUSL_ID  ASC,CUSTCO_ID  ASC);



ALTER TABLE PLT_CHT_RDY_ONOFF_HSTRY
	ADD PRIMARY KEY (CUSL_ID,CUSTCO_ID);



CREATE TABLE PLT_CHT_STNG
(
	STNG_ID               BIGINT  NOT NULL ,
	STNG_CD               VARCHAR(60)  NULL ,
	STNG_NM               VARCHAR(300)  NULL ,
	STNG_VL               VARCHAR(60)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	CUSTCO_ID             BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_STNG_PK ON PLT_CHT_STNG
(STNG_ID  ASC);



ALTER TABLE PLT_CHT_STNG
	ADD PRIMARY KEY (STNG_ID);



CREATE TABLE PLT_CHT_SYS_MSG
(
	SYS_MSG_ID            BIGINT  NOT NULL ,
	MSG_SE_CD             VARCHAR(60)  NULL ,
	RCPTN_DSPTCH_CD       VARCHAR(60)  NULL ,
	MSG_TYPE_CD           VARCHAR(60)  NULL ,
	MSG_HR                INT  NULL ,
	MSG_CN                VARCHAR(4000)  NULL ,
	MSG_EXPLN             VARCHAR(2000)  NULL ,
	LNK_TYPE_CD           VARCHAR(60)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_CHT_SYS_MSG_PK ON PLT_CHT_SYS_MSG
(SYS_MSG_ID  ASC);



ALTER TABLE PLT_CHT_SYS_MSG
	ADD PRIMARY KEY (SYS_MSG_ID);



CREATE TABLE PLT_COMM_CD
(
	GROUP_CD_ID           VARCHAR(60)  NOT NULL ,
	CD_ID                 VARCHAR(60)  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	CD_NM                 VARCHAR(300)  NULL ,
	CD_EXPLN              VARCHAR(1000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               VARCHAR(60)  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               VARCHAR(60)  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	CD_VL                 VARCHAR(100)  NULL ,
	SYS_CD_YN             CHAR(1)  NULL 
);



CREATE UNIQUE INDEX PLT_COMM_CD_PK ON PLT_COMM_CD
(GROUP_CD_ID  ASC,CUSTCO_ID  ASC,CD_ID  ASC);



ALTER TABLE PLT_COMM_CD
	ADD PRIMARY KEY (GROUP_CD_ID,CUSTCO_ID,CD_ID);



CREATE TABLE PLT_CUSTCO
(
	CUSTCO_ID             BIGINT  NOT NULL ,
	CO_NM                 VARCHAR(60)  NULL ,
	SRVC_MAINT_YN         CHAR(1)  NULL ,
	RMRK                  VARCHAR(300)  NULL ,
	USER_LGN_SMS_CERT_YN  CHAR(1) NULL ,
	SMS_CERT_EXPRY_HR	  INT NULL ,
	RGTR_ID               VARCHAR(60)  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               VARCHAR(60)  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	ASP_CUST_KEY          VARCHAR(60)  NOT NULL ,
	API_URI               VARCHAR(300)  NULL 
);



CREATE UNIQUE INDEX PLT_CUSTCO_PK ON PLT_CUSTCO
(CUSTCO_ID  ASC);



ALTER TABLE PLT_CUSTCO
	ADD PRIMARY KEY (CUSTCO_ID);



CREATE TABLE PLT_CUSTCO_DSPTCH_NO
(
	CUSTCO_DSPTCH_NO_ID   BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	DSPTCH_NO             VARCHAR(60)  NULL ,
	RPRS_NO               VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_CUSTCO_DSPTCH_NO_PK ON PLT_CUSTCO_DSPTCH_NO
(CUSTCO_DSPTCH_NO_ID  ASC);



ALTER TABLE PLT_CUSTCO_DSPTCH_NO
	ADD PRIMARY KEY (CUSTCO_DSPTCH_NO_ID);



CREATE TABLE PLT_FILE
(
	FILE_GROUP_KEY        VARCHAR(90)  NOT NULL ,
	FILE_KEY              VARCHAR(90)  NOT NULL ,
	CUSTCO_ID             BIGINT  NULL ,
	TASK_TYPE_CD          VARCHAR(60)  NULL ,
	TRGT_TYPE_CD          VARCHAR(60)  NULL ,
	PATH_TYPE_CD          VARCHAR(60)  NULL ,
	MIME_TYPE_CD          VARCHAR(60)  NULL ,
	ACTL_FILE_NM          VARCHAR(500)  NULL ,
	STRG_FILE_NM          VARCHAR(500)  NULL ,
	FILE_PATH             VARCHAR(2000)  NULL ,
	FILE_SZ               INT  NULL ,
	FILE_EXTN             VARCHAR(60)  NULL ,
	DWNLD_CNT             INT  NULL ,
	FILE_URL              VARCHAR(600)  NULL ,
	FILE_BLOB             VARCHAR(1000)  NULL ,
	ACS_KEY               VARCHAR(1000)  NULL ,
	FILE_ACS_TYPE_CD      VARCHAR(60)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_FILE_PK ON PLT_FILE
(FILE_GROUP_KEY  ASC,FILE_KEY  ASC);



ALTER TABLE PLT_FILE
	ADD PRIMARY KEY (FILE_GROUP_KEY,FILE_KEY);



CREATE TABLE PLT_LAYOUT_CLSF
(
	LAYOUT_CLSF_ID        BIGINT  NOT NULL ,
	CLSF_NM               VARCHAR(100)  NULL ,
	ICON_FILE_GROUP_KEY   VARCHAR(90)  NULL ,
	EXPLN                 VARCHAR(2000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_LAYOUT_CLSF_PK ON PLT_LAYOUT_CLSF
(LAYOUT_CLSF_ID  ASC);



ALTER TABLE PLT_LAYOUT_CLSF
	ADD PRIMARY KEY (LAYOUT_CLSF_ID);



CREATE TABLE PLT_LKAG_CD_MNG
(
	LKAG_GROUP_CD_ID      VARCHAR(60)  NOT NULL ,
	LKAG_CD_ID            VARCHAR(60)  NOT NULL ,
	LKAG_CD_VL            VARCHAR(100)  NULL ,
	LKAG_CD_NM            VARCHAR(100)  NULL ,
	EXPLN                 VARCHAR(2000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	LKAG_MST_ID           BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_CD_MNG_PK ON PLT_LKAG_CD_MNG
(LKAG_GROUP_CD_ID  ASC,LKAG_CD_ID  ASC,LKAG_MST_ID  ASC);



ALTER TABLE PLT_LKAG_CD_MNG
	ADD PRIMARY KEY (LKAG_GROUP_CD_ID,LKAG_CD_ID,LKAG_MST_ID);



CREATE INDEX PLT_LKAG_CD_MNG_F1 ON PLT_LKAG_CD_MNG
(LKAG_MST_ID  ASC);



CREATE TABLE PLT_LKAG_HEAD
(
	HEAD_ID               BIGINT  NOT NULL ,
	PARAM_COL_NM          VARCHAR(200)  NULL ,
	KEY_VL                VARCHAR(500)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	CERT_CUSTCO_LKAG_ID   BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_HEAD_PK ON PLT_LKAG_HEAD
(HEAD_ID  ASC);



ALTER TABLE PLT_LKAG_HEAD
	ADD PRIMARY KEY (HEAD_ID);



CREATE INDEX PLT_LKAG_HEAD_F1 ON PLT_LKAG_HEAD
(CERT_CUSTCO_LKAG_ID  ASC);



CREATE TABLE PLT_LKAG_LNKG_TBL
(
	LNKG_TBL_ID           BIGINT  NOT NULL ,
	TBL_NM                VARCHAR(100)  NULL ,
	COL_NM                VARCHAR(100)  NULL ,
	ATTR_ID               BIGINT  NOT NULL ,
	KEY_COL               VARCHAR(100)  NULL ,
	CERT_CUSTCO_ID        BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_LNKG_TBL_PK ON PLT_LKAG_LNKG_TBL
(LNKG_TBL_ID  ASC);



ALTER TABLE PLT_LKAG_LNKG_TBL
	ADD PRIMARY KEY (LNKG_TBL_ID);



CREATE INDEX PLT_LKAG_LNKG_TBL_F1 ON PLT_LKAG_LNKG_TBL
(CERT_CUSTCO_ID  ASC);



CREATE TABLE PLT_LKAG_MNG
(
	LKAG_ID               BIGINT  NOT NULL ,
	LKAG_MST_ID           BIGINT  NULL ,
	LKAG_NM               VARCHAR(200)  NULL ,
	LKAG_SE_CD            VARCHAR(60)  NULL ,
	RQST_SE_CD            VARCHAR(60)  NULL ,
	RSPNS_DATA_CD         VARCHAR(60)  NULL ,
	LKAG_URI              VARCHAR(1000)  NULL ,
	PARAM_DLVR_TYPE_CD    VARCHAR(60)  NULL ,
	RQST_DATA_CD          VARCHAR(60)  NULL ,
	PARAM_ENCPT_MTHD_CD   VARCHAR(60)  NULL ,
	PARAM_ENCPT_KEY       VARCHAR(500)  NULL ,
	RSPNS_DECPT_MTHD_CD   VARCHAR(60)  NULL ,
	RSPNS_DECPT_KEY       VARCHAR(500)  NULL ,
	EXPLN                 VARCHAR(2000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_MNG_PK ON PLT_LKAG_MNG
(LKAG_ID  ASC);



ALTER TABLE PLT_LKAG_MNG
	ADD PRIMARY KEY (LKAG_ID);



CREATE INDEX PLT_LKAG_MNG_F1 ON PLT_LKAG_MNG
(LKAG_MST_ID  ASC);



CREATE TABLE PLT_LKAG_MST
(
	LKAG_MST_ID           BIGINT  NOT NULL ,
	MST_NM                VARCHAR(200)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	LKAG_BEAN_ID          VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_MST_PK ON PLT_LKAG_MST
(LKAG_MST_ID  ASC);



ALTER TABLE PLT_LKAG_MST
	ADD PRIMARY KEY (LKAG_MST_ID);



CREATE TABLE PLT_LKAG_PARAM_ARTCL
(
	PARAM_ARTCL_ID        BIGINT  NOT NULL ,
	UP_ARTCL_ID           BIGINT  NULL ,
	LKAG_ID               BIGINT  NULL ,
	COL_NM                VARCHAR(100)  NULL ,
	ARTCL_NM              VARCHAR(100)  NULL ,
	DATA_TYPE_CD          VARCHAR(60)  NULL ,
	DATA_TYPE_FMT_CD      VARCHAR(60)  NULL ,
	ESNTL_YN              CHAR(1)  NULL ,
	ENCPT_YN              CHAR(1)  NULL ,
	BSC_VL                VARCHAR(100)  NULL ,
	EXPLN                 VARCHAR(2000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	RSPNS_ARTCL_ID        BIGINT  NULL ,
	LKAG_GROUP_CD_ID      VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_PARAM_ARTCL_PK ON PLT_LKAG_PARAM_ARTCL
(PARAM_ARTCL_ID  ASC);



ALTER TABLE PLT_LKAG_PARAM_ARTCL
	ADD PRIMARY KEY (PARAM_ARTCL_ID);



CREATE INDEX PLT_LKAG_PARAM_ARTCL_F1 ON PLT_LKAG_PARAM_ARTCL
(LKAG_ID  ASC);



CREATE INDEX PLT_LKAG_PARAM_ARTCL_F3 ON PLT_LKAG_PARAM_ARTCL
(RSPNS_ARTCL_ID  ASC);



CREATE INDEX PLT_LKAG_PARAM_ARTCL_F4 ON PLT_LKAG_PARAM_ARTCL
(UP_ARTCL_ID  ASC);



CREATE TABLE PLT_LKAG_PARAM_LNKG
(
	PARAM_ARTCL_ID        BIGINT  NOT NULL ,
	LNKG_TBL_ID           BIGINT  NOT NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_PARAM_LNKG_PK ON PLT_LKAG_PARAM_LNKG
(LNKG_TBL_ID  ASC,PARAM_ARTCL_ID  ASC);



ALTER TABLE PLT_LKAG_PARAM_LNKG
	ADD PRIMARY KEY (LNKG_TBL_ID,PARAM_ARTCL_ID);



CREATE INDEX PLT_LKAG_PARAM_LNKG_F1 ON PLT_LKAG_PARAM_LNKG
(LNKG_TBL_ID  ASC);



CREATE INDEX PLT_LKAG_PARAM_LNKG_F2 ON PLT_LKAG_PARAM_LNKG
(PARAM_ARTCL_ID  ASC);



CREATE TABLE PLT_LKAG_RSPNS_ARTCL
(
	RSPNS_ARTCL_ID        BIGINT  NOT NULL ,
	UP_ARTCL_ID           BIGINT  NULL ,
	LKAG_ID               BIGINT  NULL ,
	COL_NM                VARCHAR(100)  NULL ,
	ARTCL_NM              VARCHAR(100)  NULL ,
	DATA_TYPE_CD          VARCHAR(60)  NULL ,
	DATA_TYPE_FMT_CD      VARCHAR(60)  NULL ,
	ENCPT_YN              CHAR(1)  NULL ,
	EXPLN                 VARCHAR(2000)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	LKAG_GROUP_CD_ID      VARCHAR(60)  NULL 
);



CREATE UNIQUE INDEX PLT_LKAG_RSPNS_ARTCL_PK ON PLT_LKAG_RSPNS_ARTCL
(RSPNS_ARTCL_ID  ASC);



ALTER TABLE PLT_LKAG_RSPNS_ARTCL
	ADD PRIMARY KEY (RSPNS_ARTCL_ID);



CREATE INDEX PLT_LKAG_RSPNS_ARTCL_F1 ON PLT_LKAG_RSPNS_ARTCL
(UP_ARTCL_ID  ASC);



CREATE INDEX PLT_LKAG_RSPNS_ARTCL_F2 ON PLT_LKAG_RSPNS_ARTCL
(LKAG_ID  ASC);



CREATE TABLE PLT_MENU
(
	MENU_ID               BIGINT  NOT NULL ,
	UP_MENU_ID            BIGINT  NULL ,
	MENU_SE_CD_LVL        INT  NULL ,
	MENU_NM               VARCHAR(300)  NULL ,
	MENU_EXPLN            VARCHAR(2000)  NULL ,
	POPUP_FILE_NM         VARCHAR(500)  NULL ,
	PRGRM_PARAM           VARCHAR(600)  NULL ,
	VIEW_TRGT             VARCHAR(320)  NULL ,
	PATH_NM               VARCHAR(320)  NULL ,
	POPUP_WD_SZ           INT  NULL ,
	POPUP_HT_SZ           INT  NULL ,
	ICON_CLASS_NM         VARCHAR(100)  NULL ,
	INQ_AUTHRT            INT  NULL ,
	PRCS_AUTHRT           INT  NULL ,
	DEL_AUTHRT            INT  NULL ,
	OTPT_AUTHRT           INT  NULL ,
	EXCL_AUTHRT           INT  NULL ,
	ADD_AUTHRT            INT  NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	ACT_NM                VARCHAR(80)  NULL ,
	LNKG_MENU_ID          BIGINT  NULL ,
	DEL_YN                CHAR(1)  NULL 
);



CREATE UNIQUE INDEX PLT_MENU_PK ON PLT_MENU
(MENU_ID  ASC);



ALTER TABLE PLT_MENU
	ADD PRIMARY KEY (MENU_ID);



CREATE INDEX PLT_MENU_F1 ON PLT_MENU
(LNKG_MENU_ID  ASC);



CREATE INDEX PLT_MENU_F2 ON PLT_MENU
(UP_MENU_ID  ASC);



CREATE TABLE PLT_OGNZ
(
	DEPT_ID               BIGINT  NOT NULL ,
	DEPT_NM               VARCHAR(100)  NULL ,
	UP_DEPT_ID            BIGINT  NULL ,
	DEPT_SE_CD            VARCHAR(60)  NULL ,
	DEPT_CRT_YMD          CHAR(8)  NULL ,
	DEPT_ABL_YMD          CHAR(8)  NULL ,
	SCRN_INDCT_YN         CHAR(1)  NULL ,
	BLDG_PSTN             VARCHAR(1000)  NULL ,
	BLDG_NM               VARCHAR(100)  NULL ,
	BLDG_NOFL             INT  NULL ,
	USE_YN                CHAR(1)  NULL ,
	SORT_ORD              INT  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	OFC_NO                VARCHAR(20)  NULL ,
	ASP_CUST_KEY          VARCHAR(60)  NULL ,
	DEL_YN                CHAR(1)  NULL ,
	CUSTCO_ID             BIGINT  NULL ,
	UDGD_YN               CHAR(1)  NULL 
);



CREATE UNIQUE INDEX PLT_OGNZ_PK ON PLT_OGNZ
(DEPT_ID  ASC);



ALTER TABLE PLT_OGNZ
	ADD PRIMARY KEY (DEPT_ID);



CREATE INDEX PLT_OGNZ_F1 ON PLT_OGNZ
(UP_DEPT_ID  ASC);



CREATE TABLE PLT_PHN_IP_EXT
(
	PHN_IP_EXT_ID         BIGINT  NOT NULL ,
	CUSTCO_ID             BIGINT  NOT NULL ,
	DEPT_ID               BIGINT  NOT NULL ,
	USER_ID               BIGINT  NOT NULL ,
	IP                    VARCHAR(100)  NULL ,
	EXT_NO                VARCHAR(60)  NULL ,
	PDS_EXT_NO            VARCHAR(60)  NULL ,
	RMRK                  VARCHAR(4000)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	MDFR_ID               BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_PHN_IP_EXT_PK ON PLT_PHN_IP_EXT
(PHN_IP_EXT_ID  ASC);



ALTER TABLE PLT_PHN_IP_EXT
	ADD PRIMARY KEY (PHN_IP_EXT_ID);



CREATE TABLE PLT_TBL_SEQ
(
	COL_ID                VARCHAR(40)  NOT NULL ,
	SEQ_VL                INT  NULL 
);



CREATE UNIQUE INDEX PLT_TBL_SEQ_PK ON PLT_TBL_SEQ
(COL_ID  ASC);



ALTER TABLE PLT_TBL_SEQ
	ADD PRIMARY KEY (COL_ID);



CREATE TABLE PLT_USER
(
	USER_ID               BIGINT  NOT NULL ,
	USER_NM               VARCHAR(300)  NULL ,
	USER_NNM              VARCHAR(300)  NULL ,
	PSWD                  VARCHAR(300)  NULL ,
	CNTN_IP               VARCHAR(100)  NULL ,
	PRST_LGN_YN           CHAR(1)  NULL ,
	DPCN_LGN_PM_YN		  CHAR(1)  NULL ,
	PSWD_FAIL_CNT         INT  NULL ,
	BRDT                  CHAR(8)  NULL ,
	MBL_PHN_NO            VARCHAR(60)  NULL ,
	EML                   VARCHAR(60)  NULL ,
	SOLAR_SE_CD           VARCHAR(60)  NULL ,
	JNCMP_YMD             CHAR(8)  NULL ,
	RSGNTN_YMD            CHAR(8)  NULL ,
	USER_SE_CD            VARCHAR(60)  NULL ,
	JBTTL_CD              VARCHAR(60)  NULL ,
	USE_YN                CHAR(1)  NULL ,
	PSWD_MDFCN_DT         VARCHAR(14)  NULL ,
	PSWD_STTS             VARCHAR(60)  NULL ,
	USER_CERT_YN          CHAR(1)  NULL ,
	PSWD_ENCPT_CD         VARCHAR(300)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	TOP_MSG               VARCHAR(1000)  NULL ,
	ICON                  VARCHAR(100)  NULL ,
	CLBK_YN               CHAR(1)  NULL ,
	LGN_ID                VARCHAR(60)  NULL ,
	USER_STTS_CD          VARCHAR(60)  NULL ,
	TOKEN				  VARCHAR(200)  NULL ,
	TOKEN_REG_DT		  VARCHAR(14)  NULL ,
	RSVT_ALTMNT_USE_YN	  CHAR(1)  NULL
);



CREATE UNIQUE INDEX PLT_USER_PK ON PLT_USER
(USER_ID  ASC);



ALTER TABLE PLT_USER
	ADD PRIMARY KEY (USER_ID);



CREATE TABLE PLT_USER_AUTHRT
(
	AUTHRT_GROUP_ID       BIGINT  NOT NULL ,
	USER_ID               BIGINT  NOT NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL 
);



CREATE UNIQUE INDEX PLT_USER_AUTHRT_PK ON PLT_USER_AUTHRT
(AUTHRT_GROUP_ID  ASC,USER_ID  ASC);



ALTER TABLE PLT_USER_AUTHRT
	ADD PRIMARY KEY (AUTHRT_GROUP_ID,USER_ID);



CREATE INDEX PLT_USER_AUTHRT_F1 ON PLT_USER_AUTHRT
(AUTHRT_GROUP_ID  ASC);



CREATE INDEX PLT_USER_AUTHRT_F2 ON PLT_USER_AUTHRT
(USER_ID  ASC);



CREATE TABLE PLT_USER_LOG
(
	USER_LOG_ID           BIGINT  NOT NULL ,
	USER_ID               BIGINT  NULL ,
	TASK_SE_CD            VARCHAR(60)  NULL ,
	CNTN_IP               VARCHAR(100)  NULL ,
	ETC_INFO_01           VARCHAR(1000)  NULL ,
	ETC_INFO_02           VARCHAR(1000)  NULL ,
	ETC_INFO_03           VARCHAR(1000)  NULL ,
	ETC_INFO_04           VARCHAR(1000)  NULL ,
	ETC_INFO_05           VARCHAR(1000)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_USER_LOG_PK ON PLT_USER_LOG
(USER_LOG_ID  ASC);



ALTER TABLE PLT_USER_LOG
	ADD PRIMARY KEY (USER_LOG_ID);



CREATE INDEX PLT_USER_LOG_F1 ON PLT_USER_LOG
(USER_ID  ASC);



CREATE TABLE PLT_USER_OGNZ
(
	USER_ID               BIGINT  NOT NULL ,
	DEPT_ID               BIGINT  NOT NULL ,
	USE_YN                CHAR(1)  NULL ,
	REG_DT                VARCHAR(14)  NOT NULL ,
	MDFR_ID               BIGINT  NULL ,
	MDFCN_DT              VARCHAR(14)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	SORT_ORD              INT  NULL ,
	CUSTCO_ID             BIGINT  NULL 
);



CREATE UNIQUE INDEX PLT_USER_OGNZ_PK ON PLT_USER_OGNZ
(USER_ID  ASC,DEPT_ID  ASC);



ALTER TABLE PLT_USER_OGNZ
	ADD PRIMARY KEY (USER_ID,DEPT_ID);



CREATE INDEX PLT_USER_OGNZ_F1 ON PLT_USER_OGNZ
(USER_ID  ASC);



CREATE INDEX PLT_USER_OGNZ_F2 ON PLT_USER_OGNZ
(DEPT_ID  ASC);



CREATE TABLE PLT_USER_PSWD_LOG
(
	PSWD_LOG_ID           BIGINT  NOT NULL ,
	USER_ID               BIGINT  NULL ,
	TASK_SE_CD            VARCHAR(60)  NULL ,
	CNTN_IP               VARCHAR(100)  NULL ,
	ETC_INFO_01           VARCHAR(1000)  NULL ,
	ETC_INFO_02           VARCHAR(1000)  NULL ,
	ETC_INFO_03           VARCHAR(1000)  NULL ,
	ETC_INFO_04           VARCHAR(1000)  NULL ,
	ETC_INFO_05           VARCHAR(1000)  NULL ,
	RGTR_ID               BIGINT  NOT NULL ,
	REG_DT                VARCHAR(14)  NOT NULL 
);



CREATE UNIQUE INDEX PLT_USER_PSWD_LOG_PK ON PLT_USER_PSWD_LOG
(PSWD_LOG_ID  ASC);



ALTER TABLE PLT_USER_PSWD_LOG
	ADD PRIMARY KEY (PSWD_LOG_ID);



CREATE INDEX PLT_USER_PSWD_LOG_F1 ON PLT_USER_PSWD_LOG
(PSWD_LOG_ID  ASC);



CREATE INDEX PLT_USER_PSWD_LOG_F2 ON PLT_USER_PSWD_LOG
(USER_ID  ASC);



ALTER TABLE PLT_AUTHRT_GROUP_PRGRM
	ADD CONSTRAINT  R_AUTHRT_GROUP_PRGRM_2__AUTHRT FOREIGN KEY (AUTHRT_GROUP_ID) REFERENCES PLT_AUTHRT(AUTHRT_GROUP_ID);



ALTER TABLE PLT_AUTHRT_GROUP_PRGRM
	ADD CONSTRAINT  R_AUTHRT_GROUP_PRGRM_2__MENU_c FOREIGN KEY (MENU_ID) REFERENCES PLT_MENU(MENU_ID);



ALTER TABLE PLT_BTN
	ADD CONSTRAINT  R_BTN_2__MENU_27 FOREIGN KEY (MENU_ID) REFERENCES PLT_MENU(MENU_ID);



ALTER TABLE PLT_BTN_AUTHRT
	ADD CONSTRAINT  R_BTN_AUTHRT_2__AUTHRT_GROUP_P FOREIGN KEY (AUTHRT_GROUP_ID,MENU_ID) REFERENCES PLT_AUTHRT_GROUP_PRGRM(AUTHRT_GROUP_ID,MENU_ID);



ALTER TABLE PLT_BTN_AUTHRT
	ADD CONSTRAINT  R_BTN_AUTHRT_2__BTN_41 FOREIGN KEY (BTN_ID) REFERENCES PLT_BTN(BTN_ID);



ALTER TABLE PLT_CERT_CUSTCO
	ADD CONSTRAINT  R_CERT_CUSTCO_2__CERT_IPCC_SRV FOREIGN KEY (IPCC_SRVR_ID) REFERENCES PLT_CERT_IPCC_SRVR(IPCC_SRVR_ID);



ALTER TABLE PLT_CERT_CUSTCO
	ADD CONSTRAINT  R_CERT_CUSTCO_2__CERT_SRVC_GDS FOREIGN KEY (SRVC_GDS_ID) REFERENCES PLT_CERT_SRVC_GDS(SRVC_GDS_ID);



ALTER TABLE PLT_CERT_CUSTCO_CHN
	ADD CONSTRAINT  R_CERT_CUSTCO_CHN_2__CERT_CUST FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_DSPTCH_NO
	ADD CONSTRAINT  R_CERT_CUSTCO_DSPTCH_NO_2__CER FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_LANG
	ADD CONSTRAINT  R_CERT_CUSTCO_LANG_2__CERT_CUS FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_LKAG
	ADD CONSTRAINT  R_CERT_CUSTCO_LKAG_2__CERT_CUS FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_LKAG
	ADD CONSTRAINT  R_CERT_CUSTCO_LKAG_2__LKAG_MNG FOREIGN KEY (LKAG_ID) REFERENCES PLT_LKAG_MNG(LKAG_ID);



ALTER TABLE PLT_CERT_CUSTCO_SRVC
	ADD CONSTRAINT  R_CERT_CUSTCO_SRVC_2__CERT_CUS FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_SRVC
	ADD CONSTRAINT  R_CERT_CUSTCO_SRVC_2__CERT_SRV FOREIGN KEY (SRVC_GDS_DTL_ID) REFERENCES PLT_CERT_SRVC_GDS_DTL(SRVC_GDS_DTL_ID);



ALTER TABLE PLT_CERT_CUSTCO_SRVC_INST
	ADD CONSTRAINT  R_CERT_CUSTCO_SRVC_INST_2__CER FOREIGN KEY (CERT_CUSTCO_ID,SRVC_GDS_DTL_ID) REFERENCES PLT_CERT_CUSTCO_SRVC_KEY(CERT_CUSTCO_ID,SRVC_GDS_DTL_ID);



ALTER TABLE PLT_CERT_CUSTCO_SRVC_KEY
	ADD CONSTRAINT  R_CERT_CUSTCO_SRVC_KEY_2__CERT FOREIGN KEY (CERT_CUSTCO_ID,SRVC_GDS_DTL_ID) REFERENCES PLT_CERT_CUSTCO_SRVC(CERT_CUSTCO_ID,SRVC_GDS_DTL_ID);



ALTER TABLE PLT_CERT_CUSTCO_USER
	ADD CONSTRAINT  R_CERT_CUSTCO_CUST_2__CERT_CU FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_CERT_CUSTCO_USER
	ADD CONSTRAINT  R_CERT_CUSTCO_CUST_2__CERT_CU2 FOREIGN KEY (CERT_USER_ID) REFERENCES PLT_CERT_USER(CERT_USER_ID);



ALTER TABLE PLT_CERT_SRVC_GDS_DTL
	ADD CONSTRAINT  R_CERT_SRVC_GDS_DTL_2__CERT_SR FOREIGN KEY (SRVC_GDS_ID) REFERENCES PLT_CERT_SRVC_GDS(SRVC_GDS_ID);



ALTER TABLE PLT_LKAG_CD_MNG
	ADD CONSTRAINT  R_LKAG_CD_MNG_2__LKAG_MST_c1 FOREIGN KEY (LKAG_MST_ID) REFERENCES PLT_LKAG_MST(LKAG_MST_ID);



ALTER TABLE PLT_LKAG_HEAD
	ADD CONSTRAINT  R_LKAG_HEAD_2__CERT_CUSTCO_LKA FOREIGN KEY (CERT_CUSTCO_LKAG_ID) REFERENCES PLT_CERT_CUSTCO_LKAG(CERT_CUSTCO_LKAG_ID);



ALTER TABLE PLT_LKAG_LNKG_TBL
	ADD CONSTRAINT  R_LKAG_LNKG_TBL_2__CERT_CUSTCO FOREIGN KEY (CERT_CUSTCO_ID) REFERENCES PLT_CERT_CUSTCO(CERT_CUSTCO_ID);



ALTER TABLE PLT_LKAG_MNG
	ADD CONSTRAINT  R_LKAG_MNG_2__LKAG_MST_82 FOREIGN KEY (LKAG_MST_ID) REFERENCES PLT_LKAG_MST(LKAG_MST_ID);



ALTER TABLE PLT_LKAG_PARAM_ARTCL
	ADD CONSTRAINT  R_LKAG_PARAM_ARTCL_2__LKAG_MNG FOREIGN KEY (LKAG_ID) REFERENCES PLT_LKAG_MNG(LKAG_ID);



ALTER TABLE PLT_LKAG_PARAM_ARTCL
	ADD CONSTRAINT  R_LKAG_PARAM_ARTCL_2__LKAG_RSP FOREIGN KEY (RSPNS_ARTCL_ID) REFERENCES PLT_LKAG_RSPNS_ARTCL(RSPNS_ARTCL_ID);



ALTER TABLE PLT_LKAG_PARAM_ARTCL
	ADD CONSTRAINT  R_LKAG_PARAM_ARTCL_2__LKAG_PAR FOREIGN KEY (UP_ARTCL_ID) REFERENCES PLT_LKAG_PARAM_ARTCL(PARAM_ARTCL_ID);



ALTER TABLE PLT_LKAG_PARAM_LNKG
	ADD CONSTRAINT  R_LKAG_PARAM_LNKG_2__LKAG_LNKG FOREIGN KEY (LNKG_TBL_ID) REFERENCES PLT_LKAG_LNKG_TBL(LNKG_TBL_ID);



ALTER TABLE PLT_LKAG_PARAM_LNKG
	ADD CONSTRAINT  R_LKAG_PARAM_LNKG_2__LKAG_PARA FOREIGN KEY (PARAM_ARTCL_ID) REFERENCES PLT_LKAG_PARAM_ARTCL(PARAM_ARTCL_ID);



ALTER TABLE PLT_LKAG_RSPNS_ARTCL
	ADD CONSTRAINT  R_LKAG_RSPNS_ARTCL_2__LKAG_RSP FOREIGN KEY (UP_ARTCL_ID) REFERENCES PLT_LKAG_RSPNS_ARTCL(RSPNS_ARTCL_ID);



ALTER TABLE PLT_LKAG_RSPNS_ARTCL
	ADD CONSTRAINT  R_LKAG_RSPNS_ARTCL_2__LKAG_MNG FOREIGN KEY (LKAG_ID) REFERENCES PLT_LKAG_MNG(LKAG_ID);



ALTER TABLE PLT_MENU
	ADD CONSTRAINT  R_MENU_2__MENU_cd FOREIGN KEY (LNKG_MENU_ID) REFERENCES PLT_MENU(MENU_ID);



ALTER TABLE PLT_MENU
	ADD CONSTRAINT  R_MENU_2__MENU_e4 FOREIGN KEY (UP_MENU_ID) REFERENCES PLT_MENU(MENU_ID);



ALTER TABLE PLT_OGNZ
	ADD CONSTRAINT  R_OGNZ_2__OGNZ_99 FOREIGN KEY (UP_DEPT_ID) REFERENCES PLT_OGNZ(DEPT_ID);



ALTER TABLE PLT_USER_AUTHRT
	ADD CONSTRAINT  R_USER_AUTHRT_2__AUTHRT_ea FOREIGN KEY (AUTHRT_GROUP_ID) REFERENCES PLT_AUTHRT(AUTHRT_GROUP_ID);



ALTER TABLE PLT_USER_AUTHRT
	ADD CONSTRAINT  R_USER_AUTHRT_2__USER_e0 FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_USER_LOG
	ADD CONSTRAINT  R_USER_LOG_2__USER_de FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_USER_OGNZ
	ADD CONSTRAINT  R_USER_OGNZ_2__USER_3f FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



ALTER TABLE PLT_USER_OGNZ
	ADD CONSTRAINT  R_USER_OGNZ_2__OGNZ_f8 FOREIGN KEY (DEPT_ID) REFERENCES PLT_OGNZ(DEPT_ID);



ALTER TABLE PLT_USER_PSWD_LOG
	ADD CONSTRAINT  R_USER_PSWD_LOG_2__USER_LOG_4c FOREIGN KEY (PSWD_LOG_ID) REFERENCES PLT_USER_LOG(USER_LOG_ID);



ALTER TABLE PLT_USER_PSWD_LOG
	ADD CONSTRAINT  R_USER_PSWD_LOG_2__USER_dd FOREIGN KEY (USER_ID) REFERENCES PLT_USER(USER_ID);



COMMENT ON TABLE PLT_AUTHRT IS '권한';
COMMENT ON COLUMN PLT_AUTHRT.AUTHRT_GROUP_ID IS '권한_그룹_ID';
COMMENT ON COLUMN PLT_AUTHRT.AUTHRT_GROUP_NM IS '권한_그룹_명';
COMMENT ON COLUMN PLT_AUTHRT.GROUP_EXPLN IS '그룹_설명';
COMMENT ON COLUMN PLT_AUTHRT.MNGR_PM_CD IS '관리자_허용_코드';
COMMENT ON COLUMN PLT_AUTHRT.ETC_INFO_01 IS '기타_정보_01';
COMMENT ON COLUMN PLT_AUTHRT.ETC_INFO_02 IS '기타_정보_02';
COMMENT ON COLUMN PLT_AUTHRT.ETC_INFO_03 IS '기타_정보_03';
COMMENT ON COLUMN PLT_AUTHRT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_AUTHRT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_AUTHRT.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_AUTHRT.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_AUTHRT.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_AUTHRT.USER_SE_CD IS '사용자_구분_코드';

COMMENT ON TABLE PLT_AUTHRT_GROUP_PRGRM IS '권한_그룹_프로그램';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.AUTHRT_GROUP_ID IS '권한_그룹_ID';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.MENU_ID IS '메뉴_ID';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.INQ_AUTHRT IS '조회_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.PRCS_AUTHRT IS '처리_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.DEL_AUTHRT IS '삭제_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.OTPT_AUTHRT IS '출력_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.EXCL_AUTHRT IS '엑셀_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.ADD_AUTHRT IS '추가_권한';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_AUTHRT_GROUP_PRGRM.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_BTN IS '버튼';
COMMENT ON COLUMN PLT_BTN.BTN_ID IS '버튼_ID';
COMMENT ON COLUMN PLT_BTN.MENU_ID IS '메뉴_ID';
COMMENT ON COLUMN PLT_BTN.SCRN_BTN_ID IS '화면_버튼_ID';
COMMENT ON COLUMN PLT_BTN.SCRN_BTN_NM IS '화면_버튼_명';
COMMENT ON COLUMN PLT_BTN.BTN_TYPE IS '버튼_유형';
COMMENT ON COLUMN PLT_BTN.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_BTN.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_BTN.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_BTN.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_BTN_AUTHRT IS '버튼_권한';
COMMENT ON COLUMN PLT_BTN_AUTHRT.AUTHRT_GROUP_ID IS '권한_그룹_ID';
COMMENT ON COLUMN PLT_BTN_AUTHRT.MENU_ID IS '메뉴_ID';
COMMENT ON COLUMN PLT_BTN_AUTHRT.BTN_ID IS '버튼_ID';
COMMENT ON COLUMN PLT_BTN_AUTHRT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_BTN_AUTHRT.REG_DT IS '등록_일시';

COMMENT ON TABLE PLT_CERT_CUSTCO IS '인증_고객사';
COMMENT ON COLUMN PLT_CERT_CUSTCO.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.CUSTCO_NM IS '고객사_명';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SCHEMA_ID IS '스키마_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.ASP_CUST_KEY IS 'ASP_고객_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO.CUSTCO_SE_CD IS '고객사_구분_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SIC IS '표준산업분류';
COMMENT ON COLUMN PLT_CERT_CUSTCO.CRNO IS '법인등록번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.BRNO IS '사업자등록번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.RPRS_PHN_NO IS '대표_전화_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.ZIP IS '우편번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.ADDR IS '주소';
COMMENT ON COLUMN PLT_CERT_CUSTCO.DTL_ADDR IS '상세_주소';
COMMENT ON COLUMN PLT_CERT_CUSTCO.APLY_DT IS '신청_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.APLY_SE_CD IS '신청_구분_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO.APLY_USER_NM IS '신청_사용자_명';
COMMENT ON COLUMN PLT_CERT_CUSTCO.GEND IS '성별';
COMMENT ON COLUMN PLT_CERT_CUSTCO.REL_SE_CD IS '관계_구분_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO.APLY_USER_EXT_NO IS '신청_사용자_내선_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.APLY_USER_PHN_NO IS '신청_사용자_전화_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO.EML IS '이메일';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SRVC_BGNG_DT IS '서비스_시작_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SRVC_END_DT IS '서비스_종료_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SRVC_STTS_CD IS '서비스_상태_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO.USER_ACNT_CNT IS '사용자_계정_수';
COMMENT ON COLUMN PLT_CERT_CUSTCO.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.IPCC_SRVR_ID IS 'IPCC_서버_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SRVC_CRT_DT IS '서비스_생성_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO.SRVC_GDS_ID IS '서비스_상품_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.BFR_SYS_YN IS '이전_시스템_여부';
COMMENT ON COLUMN PLT_CERT_CUSTCO.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO.USER_LGN_SMS_CERT_YN IS '사용자_로그인_SMS_인증_여부';
COMMENT ON COLUMN PLT_CERT_CUSTCO.ICON_FILE_GROUP_KEY IS '아이콘_파일_그룹_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO.IMG_FILE_GROUP_KEY IS '이미지_파일_그룹_키';

COMMENT ON TABLE PLT_CERT_CUSTCO_CHN IS '인증_고객사_채널';
COMMENT ON COLUMN PLT_CERT_CUSTCO_CHN.SNDR_KEY IS '발송자_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO_CHN.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_CHN.DSPTCH_PRF_KEY IS '발신_프로필_키';

COMMENT ON TABLE PLT_CERT_CUSTCO_DSPTCH_NO IS '인증_고객사_발신_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO_DSPTCH_NO.CERT_CUSTCO_DSPTCH_NO_ID IS '인증_고객사_발신_번호_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_DSPTCH_NO.DSPTCH_NO IS '발신_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO_DSPTCH_NO.RPRS_NO IS '대표_번호';
COMMENT ON COLUMN PLT_CERT_CUSTCO_DSPTCH_NO.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_DSPTCH_NO.DSPTCH_NM IS '발신_명';

COMMENT ON TABLE PLT_CERT_CUSTCO_LANG IS '인증_고객사_언어';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.LANG_CD IS '언어_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.YMD_EXPSR_MTHD_CD IS '일자_노출_방법_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.YMD_SE_CD IS '일자_구분_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LANG.BSC_LANG_YN IS '기본_언어_여부';

COMMENT ON TABLE PLT_CERT_CUSTCO_LKAG IS '인증_고객사_연동';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.CERT_CUSTCO_LKAG_ID IS '인증_고객사_연동_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.LKAG_ID IS '연동_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.ACS_ACNT_KEY IS '접근_계정_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.ACS_SECTY_KEY IS '접근_보안_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO_LKAG.ACS_ACNT_ID IS '접근_계정_ID';

COMMENT ON TABLE PLT_CERT_CUSTCO_SRVC IS '인증_고객사_서비스';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.SRVC_GDS_DTL_ID IS '서비스_상품_상세_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_CERT_CUSTCO_SRVC_INST IS '인증_고객사_서비스_기관';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.INST_CD IS '기관_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.SRVC_GDS_DTL_ID IS '서비스_상품_상세_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_INST.INST_NM IS '기관_명';

COMMENT ON TABLE PLT_CERT_CUSTCO_SRVC_KEY IS '인증_고객사_서비스_키';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.SRVC_GDS_DTL_ID IS '서비스_상품_상세_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.CUSTCO_CD IS '고객사_코드';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_SRVC_KEY.SRVC_KEY IS '서비스_키';

COMMENT ON TABLE PLT_CERT_CUSTCO_USER IS '인증_고객사_사용자';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.CERT_CUSTCO_ID IS '인증_고객사_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.CERT_USER_ID IS '인증_사용자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_CUSTCO_USER.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_CERT_IPCC_SRVR IS '인증_IPCC_서버';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.IPCC_SRVR_ID IS 'IPCC_서버_ID';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.SRVR_NM IS '서버_명';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.API_URI IS 'API_URI';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.SRVR_STTS_CD IS '서버_상태_코드';
COMMENT ON COLUMN PLT_CERT_IPCC_SRVR.IP IS 'IP';

COMMENT ON TABLE PLT_CERT_SRVC_GDS IS '인증_서비스_상품';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS.SRVC_GDS_ID IS '서비스_상품_ID';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS.SRVC_GDS_NM IS '서비스_상품_명';

COMMENT ON TABLE PLT_CERT_SRVC_GDS_DTL IS '인증_서비스_상품_상세';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.SRVC_GDS_DTL_ID IS '서비스_상품_상세_ID';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.SRVC_GDS_ID IS '서비스_상품_ID';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.SRVC_GDS_DTL_CD IS '서비스_상품_상세_코드';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.NTSL_YN IS '판매_여부';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CERT_SRVC_GDS_DTL.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_CERT_USER IS '인증_사용자';
COMMENT ON COLUMN PLT_CERT_USER.CERT_USER_ID IS '인증_사용자_ID';
COMMENT ON COLUMN PLT_CERT_USER.LGN_ID IS '로그인_ID';

COMMENT ON TABLE PLT_CHT_CUSTCO_SYS_MSG IS '채팅_고객사_시스템_메시지';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.SYS_MSG_ID IS '시스템_메시지_ID';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.MSG_HR IS '메시지_시간';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.MSG_TYPE_CD IS '메시지_유형_코드';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.MSG_CN IS '메시지_내용';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CHT_CUSTCO_SYS_MSG.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_CHT_RDY_ONOFF_HSTRY IS '채팅_대기_ONOFF_이력';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.CUSL_ID IS '상담사_ID';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.STTS_CD IS '상태_코드';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.CUTT_BGNG_DT IS '상담_시작_일시';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.CUTT_END_DT IS '상담_종료_일시';
COMMENT ON COLUMN PLT_CHT_RDY_ONOFF_HSTRY.PRCS_HR IS '처리_시간';

COMMENT ON TABLE PLT_CHT_STNG IS '채팅_설정';
COMMENT ON COLUMN PLT_CHT_STNG.STNG_ID IS '설정_ID';
COMMENT ON COLUMN PLT_CHT_STNG.STNG_CD IS '설정_코드';
COMMENT ON COLUMN PLT_CHT_STNG.STNG_NM IS '설정_명';
COMMENT ON COLUMN PLT_CHT_STNG.STNG_VL IS '설정_값';
COMMENT ON COLUMN PLT_CHT_STNG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CHT_STNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CHT_STNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHT_STNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CHT_STNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CHT_STNG.CUSTCO_ID IS '고객사_ID';

COMMENT ON TABLE PLT_CHT_SYS_MSG IS '채팅_시스템_메시지';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.SYS_MSG_ID IS '시스템_메시지_ID';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MSG_SE_CD IS '메시지_구분_코드';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.RCPTN_DSPTCH_CD IS '수신_발신_코드';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MSG_TYPE_CD IS '메시지_유형_코드';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MSG_HR IS '메시지_시간';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MSG_CN IS '메시지_내용';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MSG_EXPLN IS '메시지_설명';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.LNK_TYPE_CD IS '링크_유형_코드';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CHT_SYS_MSG.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_COMM_CD IS '공통_코드';
COMMENT ON COLUMN PLT_COMM_CD.GROUP_CD_ID IS '그룹_코드_ID';
COMMENT ON COLUMN PLT_COMM_CD.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_COMM_CD.CD_ID IS '코드_ID';
COMMENT ON COLUMN PLT_COMM_CD.CD_NM IS '코드_명';
COMMENT ON COLUMN PLT_COMM_CD.CD_EXPLN IS '코드_설명';
COMMENT ON COLUMN PLT_COMM_CD.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_COMM_CD.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_COMM_CD.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_COMM_CD.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_COMM_CD.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_COMM_CD.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_COMM_CD.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_COMM_CD.CD_VL IS '코드_값';
COMMENT ON COLUMN PLT_COMM_CD.SYS_CD_YN IS '시스템_코드_여부';

COMMENT ON TABLE PLT_CUSTCO IS '고객사';
COMMENT ON COLUMN PLT_CUSTCO.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CUSTCO.CO_NM IS '회사_명';
COMMENT ON COLUMN PLT_CUSTCO.SRVC_MAINT_YN IS '서비스_유지_여부';
COMMENT ON COLUMN PLT_CUSTCO.RMRK IS '비고';
COMMENT ON COLUMN PLT_CUSTCO.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_CUSTCO.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_CUSTCO.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_CUSTCO.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_CUSTCO.ASP_CUST_KEY IS 'ASP_고객_키';
COMMENT ON COLUMN PLT_CUSTCO.API_URI IS 'API_URI';
COMMENT ON COLUMN PLT_CUSTCO.USER_LGN_SMS_CERT_YN IS '사용자_로그인_SMS_인증_여부';
COMMENT ON COLUMN PLT_CUSTCO.SMS_CERT_EXPRY_HR IS 'SMS_인증_만료_시간';

COMMENT ON TABLE PLT_CUSTCO_DSPTCH_NO IS '고객사_발신_번호';
COMMENT ON COLUMN PLT_CUSTCO_DSPTCH_NO.CUSTCO_DSPTCH_NO_ID IS '고객사_발신_번호_ID';
COMMENT ON COLUMN PLT_CUSTCO_DSPTCH_NO.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_CUSTCO_DSPTCH_NO.DSPTCH_NO IS '발신_번호';
COMMENT ON COLUMN PLT_CUSTCO_DSPTCH_NO.RPRS_NO IS '대표_번호';

COMMENT ON TABLE PLT_FILE IS '파일';
COMMENT ON COLUMN PLT_FILE.FILE_GROUP_KEY IS '파일_그룹_키';
COMMENT ON COLUMN PLT_FILE.FILE_KEY IS '파일_키';
COMMENT ON COLUMN PLT_FILE.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_FILE.TASK_TYPE_CD IS '업무_유형_코드';
COMMENT ON COLUMN PLT_FILE.TRGT_TYPE_CD IS '대상_유형_코드';
COMMENT ON COLUMN PLT_FILE.PATH_TYPE_CD IS '경로_유형_코드';
COMMENT ON COLUMN PLT_FILE.MIME_TYPE_CD IS 'MIME_유형_코드';
COMMENT ON COLUMN PLT_FILE.ACTL_FILE_NM IS '실제_파일_명';
COMMENT ON COLUMN PLT_FILE.STRG_FILE_NM IS '저장_파일_명';
COMMENT ON COLUMN PLT_FILE.FILE_PATH IS '파일_경로';
COMMENT ON COLUMN PLT_FILE.FILE_SZ IS '파일_크기';
COMMENT ON COLUMN PLT_FILE.FILE_EXTN IS '파일_확장자';
COMMENT ON COLUMN PLT_FILE.DWNLD_CNT IS '다운로드_수';
COMMENT ON COLUMN PLT_FILE.FILE_URL IS '파일_URL';
COMMENT ON COLUMN PLT_FILE.FILE_BLOB IS '파일_BLOB';
COMMENT ON COLUMN PLT_FILE.ACS_KEY IS '접근_키';
COMMENT ON COLUMN PLT_FILE.FILE_ACS_TYPE_CD IS '파일_접근_유형_코드';
COMMENT ON COLUMN PLT_FILE.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_FILE.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_FILE.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_FILE.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_FILE.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_LAYOUT_CLSF IS '레이아웃_분류';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.LAYOUT_CLSF_ID IS '레이아웃_분류_ID';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.EXPLN IS '설명';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.ICON_FILE_GROUP_KEY IS '아이콘_파일_그룹_키';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LAYOUT_CLSF.CLSF_NM IS '분류_명';

COMMENT ON TABLE PLT_LKAG_CD_MNG IS '연동_코드_관리';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.LKAG_GROUP_CD_ID IS '연동_그룹_코드_ID';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.LKAG_CD_ID IS '연동_코드_ID';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.LKAG_MST_ID IS '연동_마스터_ID';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.LKAG_CD_VL IS '연동_코드_값';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.LKAG_CD_NM IS '연동_코드_명';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.EXPLN IS '설명';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LKAG_CD_MNG.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_LKAG_HEAD IS '연동_헤더';
COMMENT ON COLUMN PLT_LKAG_HEAD.HEAD_ID IS '헤더_ID';
COMMENT ON COLUMN PLT_LKAG_HEAD.PARAM_COL_NM IS '파라미터_컬럼_명';
COMMENT ON COLUMN PLT_LKAG_HEAD.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_HEAD.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_HEAD.KEY_VL IS '키_값';
COMMENT ON COLUMN PLT_LKAG_HEAD.CERT_CUSTCO_LKAG_ID IS '인증_고객사_연동_ID';

COMMENT ON TABLE PLT_LKAG_LNKG_TBL IS '연동_연결_테이블';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.LNKG_TBL_ID IS '연결_테이블_ID';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.TBL_NM IS '테이블_명';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.COL_NM IS '컬럼_명';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.KEY_COL IS '키_컬럼';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.ATTR_ID IS '속성_ID';
COMMENT ON COLUMN PLT_LKAG_LNKG_TBL.CERT_CUSTCO_ID IS '인증_고객사_ID';

COMMENT ON TABLE PLT_LKAG_MNG IS '연동_관리';
COMMENT ON COLUMN PLT_LKAG_MNG.LKAG_ID IS '연동_ID';
COMMENT ON COLUMN PLT_LKAG_MNG.LKAG_NM IS '연동_명';
COMMENT ON COLUMN PLT_LKAG_MNG.LKAG_SE_CD IS '연동_구분_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.RQST_SE_CD IS '의뢰_구분_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.RSPNS_DATA_CD IS '응답_자료_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.LKAG_URI IS '연동_URI';
COMMENT ON COLUMN PLT_LKAG_MNG.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LKAG_MNG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_MNG.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_MNG.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LKAG_MNG.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LKAG_MNG.PARAM_DLVR_TYPE_CD IS '파라미터_전달_유형_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.EXPLN IS '설명';
COMMENT ON COLUMN PLT_LKAG_MNG.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LKAG_MNG.PARAM_ENCPT_MTHD_CD IS '파라미터_암호화_방법_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.RSPNS_DECPT_KEY IS '응답_복호화_키';
COMMENT ON COLUMN PLT_LKAG_MNG.RSPNS_DECPT_MTHD_CD IS '응답_복호화_방법_코드';
COMMENT ON COLUMN PLT_LKAG_MNG.PARAM_ENCPT_KEY IS '파라미터_암호화_키';
COMMENT ON COLUMN PLT_LKAG_MNG.LKAG_MST_ID IS '연동_마스터_ID';
COMMENT ON COLUMN PLT_LKAG_MNG.RQST_DATA_CD IS '의뢰_자료_코드';

COMMENT ON TABLE PLT_LKAG_MST IS '연동_마스터';
COMMENT ON COLUMN PLT_LKAG_MST.LKAG_MST_ID IS '연동_마스터_ID';
COMMENT ON COLUMN PLT_LKAG_MST.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LKAG_MST.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LKAG_MST.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_MST.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_MST.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LKAG_MST.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LKAG_MST.MST_NM IS '마스터_명';
COMMENT ON COLUMN PLT_LKAG_MST.LKAG_BEAN_ID IS '연동_BEAN_ID';

COMMENT ON TABLE PLT_LKAG_PARAM_ARTCL IS '연동_파라미터_항목';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.PARAM_ARTCL_ID IS '파라미터_항목_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.UP_ARTCL_ID IS '상위_항목_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.COL_NM IS '컬럼_명';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.ARTCL_NM IS '항목_명';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.DATA_TYPE_CD IS '자료_유형_코드';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.ESNTL_YN IS '필수_여부';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.EXPLN IS '설명';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.LKAG_ID IS '연동_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.ENCPT_YN IS '암호화_여부';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.BSC_VL IS '기본_값';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.RSPNS_ARTCL_ID IS '응답_항목_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.LKAG_GROUP_CD_ID IS '연동_그룹_코드_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_ARTCL.DATA_TYPE_FMT_CD IS '자료_유형_포멧_코드';

COMMENT ON TABLE PLT_LKAG_PARAM_LNKG IS '연동_파라미터_연결';
COMMENT ON COLUMN PLT_LKAG_PARAM_LNKG.LNKG_TBL_ID IS '연결_테이블_ID';
COMMENT ON COLUMN PLT_LKAG_PARAM_LNKG.PARAM_ARTCL_ID IS '파라미터_항목_ID';

COMMENT ON TABLE PLT_LKAG_RSPNS_ARTCL IS '연동_응답_항목';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.RSPNS_ARTCL_ID IS '응답_항목_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.UP_ARTCL_ID IS '상위_항목_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.LKAG_ID IS '연동_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.COL_NM IS '컬럼_명';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.ARTCL_NM IS '항목_명';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.EXPLN IS '설명';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.DATA_TYPE_FMT_CD IS '자료_유형_포멧_코드';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.ENCPT_YN IS '암호화_여부';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.LKAG_GROUP_CD_ID IS '연동_그룹_코드_ID';
COMMENT ON COLUMN PLT_LKAG_RSPNS_ARTCL.DATA_TYPE_CD IS '자료_유형_코드';

COMMENT ON TABLE PLT_MENU IS '메뉴';
COMMENT ON COLUMN PLT_MENU.MENU_ID IS '메뉴_ID';
COMMENT ON COLUMN PLT_MENU.UP_MENU_ID IS '상위_메뉴_ID';
COMMENT ON COLUMN PLT_MENU.MENU_SE_CD_LVL IS '메뉴_구분_코드_수준';
COMMENT ON COLUMN PLT_MENU.MENU_NM IS '메뉴_명';
COMMENT ON COLUMN PLT_MENU.MENU_EXPLN IS '메뉴_설명';
COMMENT ON COLUMN PLT_MENU.POPUP_FILE_NM IS '팝업_파일_명';
COMMENT ON COLUMN PLT_MENU.PRGRM_PARAM IS '프로그램_파라미터';
COMMENT ON COLUMN PLT_MENU.VIEW_TRGT IS '뷰_대상';
COMMENT ON COLUMN PLT_MENU.PATH_NM IS '경로_명';
COMMENT ON COLUMN PLT_MENU.POPUP_WD_SZ IS '팝업_가로_크기';
COMMENT ON COLUMN PLT_MENU.POPUP_HT_SZ IS '팝업_세로_크기';
COMMENT ON COLUMN PLT_MENU.ICON_CLASS_NM IS '아이콘_클레스_명';
COMMENT ON COLUMN PLT_MENU.INQ_AUTHRT IS '조회_권한';
COMMENT ON COLUMN PLT_MENU.PRCS_AUTHRT IS '처리_권한';
COMMENT ON COLUMN PLT_MENU.DEL_AUTHRT IS '삭제_권한';
COMMENT ON COLUMN PLT_MENU.OTPT_AUTHRT IS '출력_권한';
COMMENT ON COLUMN PLT_MENU.EXCL_AUTHRT IS '엑셀_권한';
COMMENT ON COLUMN PLT_MENU.ADD_AUTHRT IS '추가_권한';
COMMENT ON COLUMN PLT_MENU.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_MENU.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_MENU.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_MENU.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_MENU.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_MENU.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_MENU.ACT_NM IS '액션_명';
COMMENT ON COLUMN PLT_MENU.LNKG_MENU_ID IS '연결_메뉴_ID';
COMMENT ON COLUMN PLT_MENU.DEL_YN IS '삭제_여부';

COMMENT ON TABLE PLT_OGNZ IS '조직';
COMMENT ON COLUMN PLT_OGNZ.DEPT_ID IS '부서_ID';
COMMENT ON COLUMN PLT_OGNZ.DEPT_NM IS '부서_명';
COMMENT ON COLUMN PLT_OGNZ.UP_DEPT_ID IS '상위_부서_ID';
COMMENT ON COLUMN PLT_OGNZ.DEPT_SE_CD IS '부서_구분_코드';
COMMENT ON COLUMN PLT_OGNZ.DEPT_CRT_YMD IS '부서_생성_일자';
COMMENT ON COLUMN PLT_OGNZ.DEPT_ABL_YMD IS '부서_폐지_일자';
COMMENT ON COLUMN PLT_OGNZ.SCRN_INDCT_YN IS '화면_표시_여부';
COMMENT ON COLUMN PLT_OGNZ.BLDG_PSTN IS '건물_위치';
COMMENT ON COLUMN PLT_OGNZ.BLDG_NM IS '건물_명';
COMMENT ON COLUMN PLT_OGNZ.BLDG_NOFL IS '건물_층수';
COMMENT ON COLUMN PLT_OGNZ.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_OGNZ.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_OGNZ.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_OGNZ.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_OGNZ.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_OGNZ.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_OGNZ.OFC_NO IS '사무실_번호';
COMMENT ON COLUMN PLT_OGNZ.ASP_CUST_KEY IS 'ASP_고객_키';
COMMENT ON COLUMN PLT_OGNZ.DEL_YN IS '삭제_여부';
COMMENT ON COLUMN PLT_OGNZ.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_OGNZ.UDGD_YN IS '지하_여부';

COMMENT ON TABLE PLT_PHN_IP_EXT IS '전화_IP_내선';
COMMENT ON COLUMN PLT_PHN_IP_EXT.PHN_IP_EXT_ID IS '전화_IP_내선_ID';
COMMENT ON COLUMN PLT_PHN_IP_EXT.CUSTCO_ID IS '고객사_ID';
COMMENT ON COLUMN PLT_PHN_IP_EXT.DEPT_ID IS '부서_ID';
COMMENT ON COLUMN PLT_PHN_IP_EXT.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_PHN_IP_EXT.IP IS 'IP';
COMMENT ON COLUMN PLT_PHN_IP_EXT.EXT_NO IS '내선_번호';
COMMENT ON COLUMN PLT_PHN_IP_EXT.PDS_EXT_NO IS 'PDS_내선_번호';
COMMENT ON COLUMN PLT_PHN_IP_EXT.RMRK IS '비고';
COMMENT ON COLUMN PLT_PHN_IP_EXT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_PHN_IP_EXT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_PHN_IP_EXT.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_PHN_IP_EXT.MDFR_ID IS '수정자_ID';

COMMENT ON TABLE PLT_TBL_SEQ IS '테이블_시퀀스';
COMMENT ON COLUMN PLT_TBL_SEQ.COL_ID IS '컬럼_ID';
COMMENT ON COLUMN PLT_TBL_SEQ.SEQ_VL IS '시퀀스_값';

COMMENT ON TABLE PLT_USER IS '사용자';
COMMENT ON COLUMN PLT_USER.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER.USER_NM IS '사용자_명';
COMMENT ON COLUMN PLT_USER.USER_NNM IS '사용자_별칭';
COMMENT ON COLUMN PLT_USER.PSWD IS '비밀번호';
COMMENT ON COLUMN PLT_USER.CNTN_IP IS '접속_IP';
COMMENT ON COLUMN PLT_USER.PRST_LGN_YN IS '현재_로그인_여부';
COMMENT ON COLUMN PLT_USER.DPCN_LGN_PM_YN IS '중복_로그인_허용_여부';
COMMENT ON COLUMN PLT_USER.PSWD_FAIL_CNT IS '비밀번호_실패_수';
COMMENT ON COLUMN PLT_USER.BRDT IS '생년월일';
COMMENT ON COLUMN PLT_USER.MBL_PHN_NO IS '휴대_전화_번호';
COMMENT ON COLUMN PLT_USER.EML IS '이메일';
COMMENT ON COLUMN PLT_USER.SOLAR_SE_CD IS '양력_구분_코드';
COMMENT ON COLUMN PLT_USER.JNCMP_YMD IS '입사_일자';
COMMENT ON COLUMN PLT_USER.RSGNTN_YMD IS '퇴사_일자';
COMMENT ON COLUMN PLT_USER.USER_SE_CD IS '사용자_구분_코드';
COMMENT ON COLUMN PLT_USER.JBTTL_CD IS '직책_코드';
COMMENT ON COLUMN PLT_USER.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_USER.PSWD_MDFCN_DT IS '비밀번호_수정_일시';
COMMENT ON COLUMN PLT_USER.PSWD_STTS IS '비밀번호_상태';
COMMENT ON COLUMN PLT_USER.USER_CERT_YN IS '사용자_인증_여부';
COMMENT ON COLUMN PLT_USER.PSWD_ENCPT_CD IS '비밀번호_암호화_코드';
COMMENT ON COLUMN PLT_USER.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_USER.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_USER.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_USER.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_USER.TOP_MSG IS '상단_메시지';
COMMENT ON COLUMN PLT_USER.ICON IS '아이콘';
COMMENT ON COLUMN PLT_USER.CLBK_YN IS '콜백_여부';
COMMENT ON COLUMN PLT_USER.LGN_ID IS '로그인_ID';
COMMENT ON COLUMN PLT_USER.USER_STTS_CD IS '사용자_상태_코드';
COMMENT ON COLUMN PLT_USER.TOKEN IS '토큰';
COMMENT ON COLUMN PLT_USER.TOKEN_REG_DT IS '토큰_등록_일시';
COMMENT ON COLUMN PLT_USER.RSVT_ALTMNT_USE_YN IS '예약_배정_사용_여부';

COMMENT ON TABLE PLT_USER_AUTHRT IS '사용자_권한';
COMMENT ON COLUMN PLT_USER_AUTHRT.AUTHRT_GROUP_ID IS '권한_그룹_ID';
COMMENT ON COLUMN PLT_USER_AUTHRT.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_AUTHRT.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_USER_AUTHRT.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_USER_AUTHRT.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_USER_AUTHRT.MDFCN_DT IS '수정_일시';

COMMENT ON TABLE PLT_USER_LOG IS '사용자_로그';
COMMENT ON COLUMN PLT_USER_LOG.USER_LOG_ID IS '사용자_로그_ID';
COMMENT ON COLUMN PLT_USER_LOG.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_LOG.TASK_SE_CD IS '업무_구분_코드';
COMMENT ON COLUMN PLT_USER_LOG.CNTN_IP IS '접속_IP';
COMMENT ON COLUMN PLT_USER_LOG.ETC_INFO_01 IS '기타_정보_01';
COMMENT ON COLUMN PLT_USER_LOG.ETC_INFO_02 IS '기타_정보_02';
COMMENT ON COLUMN PLT_USER_LOG.ETC_INFO_03 IS '기타_정보_03';
COMMENT ON COLUMN PLT_USER_LOG.ETC_INFO_04 IS '기타_정보_04';
COMMENT ON COLUMN PLT_USER_LOG.ETC_INFO_05 IS '기타_정보_05';
COMMENT ON COLUMN PLT_USER_LOG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_USER_LOG.REG_DT IS '등록_일시';

COMMENT ON TABLE PLT_USER_OGNZ IS '사용자_조직';
COMMENT ON COLUMN PLT_USER_OGNZ.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_OGNZ.DEPT_ID IS '부서_ID';
COMMENT ON COLUMN PLT_USER_OGNZ.USE_YN IS '사용_여부';
COMMENT ON COLUMN PLT_USER_OGNZ.REG_DT IS '등록_일시';
COMMENT ON COLUMN PLT_USER_OGNZ.MDFR_ID IS '수정자_ID';
COMMENT ON COLUMN PLT_USER_OGNZ.MDFCN_DT IS '수정_일시';
COMMENT ON COLUMN PLT_USER_OGNZ.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_USER_OGNZ.SORT_ORD IS '정렬_순서';
COMMENT ON COLUMN PLT_USER_OGNZ.CUSTCO_ID IS '고객사_ID';

COMMENT ON TABLE PLT_USER_PSWD_LOG IS '사용자_비밀번호_로그';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.PSWD_LOG_ID IS '비밀번호_로그_ID';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.USER_ID IS '사용자_ID';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.TASK_SE_CD IS '업무_구분_코드';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.CNTN_IP IS '접속_IP';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.ETC_INFO_01 IS '기타_정보_01';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.ETC_INFO_02 IS '기타_정보_02';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.ETC_INFO_03 IS '기타_정보_03';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.ETC_INFO_04 IS '기타_정보_04';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.ETC_INFO_05 IS '기타_정보_05';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.RGTR_ID IS '등록자_ID';
COMMENT ON COLUMN PLT_USER_PSWD_LOG.REG_DT IS '등록_일시';




